### ISSUE TITLE
Can't add more than 7 rows of containers

### ISSUE THREAD

**Issue by jorenvh1** [sonata-project/SonataPageBundle#1015]
## Subject

Currently it is not supported to add more than 7 rows of containers on a single page. Let's say I want to make a onepager template which will have 10 different kind of containers, this is not possible.

## Steps to reproduce
```
matrix:
                layout: |
                    AAAAAAAA
                    BBBBBBBB
                    CCCCCCCC
                    DDDDDDDD
                    EEEEEEEE
                    FFFFFFFF
                    GGGGGGGG
                    HHHHHHHH
```
## Expected results

Another container will show up in the admin view

## Actual results

Error is displayed because it currently only accepts a 8x7 grid

**Comment by OskarStark** [comment]
Could you provide a PR to fix this?

**Comment by jorenvh1** [comment]
@OskarStark Haven't had the time to work on this, sorry
