### ISSUE TITLE
RenderBlockCommand not compatible with Symfony 3.x

### ISSUE THREAD

**Issue by srascar** [sonata-project/SonataPageBundle#1044]
### Environment
Docker alpine

#### Sonata packages
"sonata-project/page-bundle": "^3.9"

#### Symfony packages
"symfony/symfony": "3.4.*"
```
$ composer show --latest 'symfony/*'
# Put the result here.
```

#### PHP version
"php": "^7.1"

## Subject
`RenderBlockCommand` is using the method `enterScope` of the Container object.
This method was deprecated in Symfony 2.8 and removed in Symfony 3.0
https://symfony.com/blog/new-in-symfony-2-8-deprecating-scopes-and-introducing-shared-services

## Steps to reproduce
```
$ php bin/console sonata:page:render-block sonata.page.cms.page 1 43
```
Where 1 and 43 are respectively ids of a page and a block

## Expected results
The command should dump the render of the block

## Actual results
```
In RenderBlockCommand.php line 82:

  Attempted to call an undefined method named "enterScope" of class "Container0tdawmi\a
  ppDevDebugProjectContainer".
```

**Comment by mariepierreMangeret** [comment]
Has this issue been resolved? As I have the same problem...
