### ISSUE TITLE
type check on site ID results in no sites found

### ISSUE THREAD

**Issue by RubenHollevoet** [sonata-project/SonataPageBundle#1061]
I have encountered a bug after upgrading from 3.10.0 tot 3.11.0.

In 8a50427a168d0fbc03bf5637504f3b1ec71204c1 src/Controller/PageAdminController.php:86, the check was made type sensitive. Since $siteId is a string, the siteId in the model should by definition also be of the type string. In my case id was an integer so no sites were found.
I would suggest type conversion should be added or the check should be made non type sensitive.

This issue also relates to #1048.

**Comment by p1nGgeR** [comment]
@RubenHollevoet Hi, it was fixed in the 3.11.1 version
https://github.com/sonata-project/SonataPageBundle/commit/ae701888155e295af1ac3c560b0c8cb4d1014a7c
