### ISSUE TITLE
BlockInteractor::__construct() must be an instance of Symfony\Bridge\Doctrine\RegistryInterface Registry given

### ISSUE THREAD

**Issue by grekpg** [sonata-project/SonataPageBundle#1094]
After composer update i get new errors

```
 "sonata-project/admin-bundle": "^3.48",
    "sonata-project/doctrine-orm-admin-bundle": "^3.9",
    "sonata-project/page-bundle": "^3.11",
    "sonata-project/translation-bundle": "^2.4",
    "sonata-project/user-bundle": "^4.3",
    "symfony/console": "4.3.*",
    "symfony/dotenv": "4.3.*",
    "symfony/flex": "^1.1",
    "symfony/framework-bundle": "4.3.*",
```

Argument 1 passed to Sonata\PageBundle\Entity\BlockInteractor::__construct() must be an instance of Symfony\Bridge\Doctrine\RegistryInterface, instance of Doctrine\Bundle\DoctrineBundle\Registry given,

**Comment by delboy1978uk** [comment]
They've removed the Interface
https://github.com/doctrine/DoctrineBundle/blob/master/UPGRADE-2.0.md

**Comment by OskarStark** [comment]
Can anybody provider a PR?
