### ISSUE TITLE
Changelog in master suggests that version 3.15.1 removed cocur/slugify but taged version doesn't

### ISSUE THREAD

**Issue by n3o77** [sonata-project/SonataPageBundle#1131]
Basically what the titlte says. In the master branch it's noted that with `3.15.1` the `cocur/slugify` dependency was removed, but when looking in the taged version it's still in there: https://github.com/sonata-project/SonataPageBundle/blob/3.15.1/composer.json

**Comment by VincentLanglet** [comment]
Indeed https://github.com/sonata-project/SonataPageBundle/compare/3.15.1...3.x

**Comment by greg0ire** [comment]
That's really weird:
1. I don't reproduce the issue locally
2. When I browse GH with the hash of the commit, the file looks correct: https://github.com/sonata-project/SonataPageBundle/blob/3ba7afe8fb8e2077af8787888f7fa4c75c875d4c/composer.json

**Comment by greg0ire** [comment]
Also the release page shows another hash :/ https://github.com/sonata-project/SonataPageBundle/releases/tag/3.15.1

**Comment by greg0ire** [comment]
I think I must have f**ed up somewhere when creating this release… I'm just going to release 3.15.2 . Resetting the tag to the right hash is rewriting history and should not be done.

**Comment by greg0ire** [comment]
I fixed the changelog and released 3.16.0
