### ISSUE TITLE
Error during "Create a Publication" from list view in page:  An exception has been thrown during the rendering of a template ("Notice: Array to string conversion")

### ISSUE THREAD

**Issue by wwtvishal** [sonata-project/SonataPageBundle#1134]
Hello!
Please help me to solve the issue.

Steps to reproduce the error:

Install the sonata page bundle and do the required configuration.

Go to Pages at back-end:

Pages > Manage Pages >> List View 

and checked any of the pages which you have added already or add new one and do the same.

and select the option "Create a publication" >> "OK" >> "Yes Execute" and then there will be error "An exception has been thrown during the rendering of a template ("Notice: Array to string conversion")."

![screenshot2020 03 30-14_15_55](https://user-images.githubusercontent.com/62282872/77893501-a0b0ff00-7291-11ea-8046-51e56efd9962.png)

Please note: I have tried with a fresh installation of the Sonata Page Bundle it seems there is the same error.

Please help me to solve the error or suggest me any version which is resolved with the mentioned error.

Many Thanks!!

**Comment by haivala** [comment]
I have same problem but you can create publication by editing one page and choosing publications from the side menu and adding a new one.

It's only the batch action that does not work.

**Comment by VincentLanglet** [comment]
Please use the issue template @wwtvishal. It'll be easier to help if you fill the following information.

#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
# Put the result here.
```

#### PHP version

```
$ php -v
# Put the result here.
```

Plus, when you get the error `"An exception has been thrown during the rendering of a template ("Notice: Array to string conversion"` ; don't you have a file/line where it's coming from ?

**Comment by haivala** [comment]
When you use the batch action: It created the publication but it saves something to session which gives this error when trying to load page list or tree..
resetting the user session resolves this.

**Comment by wwtvishal** [comment]
Thanks @haivala @VincentLanglet 

Here is the information @VincentLanglet 

**Sonata packages**

```
-sh-4.2$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.56.1 3.63.0 The missing Symfony A...
sonata-project/block-bundle              3.18.2 3.18.4 Symfony SonataBlockBu...
sonata-project/cache                     1.1.1  2.0.1  Cache library
sonata-project/cache-bundle              2.4.2  3.2.1  This bundle provides ...
sonata-project/core-bundle               3.17.2 3.18.0 Symfony SonataCoreBun...
sonata-project/datagrid-bundle           2.5.0  3.1.1  Symfony SonataDatagri...
sonata-project/doctrine-extensions       1.5.1  1.6.0  Doctrine2 behavioral ...
sonata-project/doctrine-orm-admin-bundle 3.13.0 3.15.0 Symfony Sonata / Inte...
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExt...
sonata-project/exporter                  2.0.1  2.2.0  Lightweight Exporter ...
sonata-project/formatter-bundle          4.1.3  4.1.3  Symfony SonataFormatt...
sonata-project/intl-bundle               2.7.0  2.7.0  Symfony SonataIntlBundle
sonata-project/media-bundle              3.22.0 3.24.0 Symfony SonataMediaBu...
sonata-project/notification-bundle       3.6.2  3.7.0  Symfony SonataNotific...
sonata-project/page-bundle               3.13.0 3.16.0 This bundle provides ...
sonata-project/seo-bundle                2.9.0  2.10.0 Symfony SonataSeoBundle
sonata-project/translation-bundle        2.4.2  2.4.2  SonataTranslationBundle
```

**Symfony packages**

`-sh-4.2$ composer show --latest 'symfony/*'
Restricting packages listed in "symfony/symfony" to "4.3.*"
symfony/asset                      v4.3.9  v4.3.11 Symfony Asset Component
symfony/browser-kit                v4.3.9  v4.3.11 Symfony BrowserKit Component
symfony/cache                      v4.3.9  v4.3.11 Symfony Cache component w...
symfony/cache-contracts            v1.1.7  v2.0.1  Generic abstractions rela...
symfony/config                     v4.3.9  v4.3.11 Symfony Config Component
symfony/console                    v4.3.9  v4.3.11 Symfony Console Component
symfony/css-selector               v4.3.9  v4.3.11 Symfony CssSelector Compo...
symfony/debug                      v4.3.9  v4.3.11 Symfony Debug Component
symfony/debug-bundle               v4.3.9  v4.3.11 Symfony DebugBundle
symfony/debug-pack                 v1.0.7  v1.0.7  A debug pack for Symfony ...
symfony/dependency-injection       v4.3.9  v4.3.11 Symfony DependencyInjecti...
symfony/doctrine-bridge            v4.3.9  v4.3.11 Symfony Doctrine Bridge
symfony/dom-crawler                v4.3.9  v4.3.11 Symfony DomCrawler Component
symfony/dotenv                     v4.3.9  v4.3.11 Registers environment var...
symfony/event-dispatcher           v4.3.9  v4.3.11 Symfony EventDispatcher C...
symfony/event-dispatcher-contracts v1.1.7  v2.0.1  Generic abstractions rela...
symfony/expression-language        v4.3.9  v4.3.11 Symfony ExpressionLanguag...
symfony/filesystem                 v4.3.9  v4.3.11 Symfony Filesystem Component
symfony/finder                     v4.3.9  v4.3.11 Symfony Finder Component
symfony/flex                       v1.6.0  v1.6.2  Composer plugin for Symfony
symfony/form                       v4.3.9  v4.3.11 Symfony Form Component
symfony/framework-bundle           v4.3.9  v4.3.11 Symfony FrameworkBundle
symfony/http-client                v4.3.9  v4.3.11 Symfony HttpClient component
symfony/http-client-contracts      v1.1.8  v2.0.1  Generic abstractions rela...
symfony/http-foundation            v4.3.9  v4.3.11 Symfony HttpFoundation Co...
symfony/http-kernel                v4.3.9  v4.3.11 Symfony HttpKernel Component
symfony/inflector                  v4.3.9  v4.3.11 Symfony Inflector Component
symfony/intl                       v4.3.9  v4.3.11 A PHP replacement layer f...
symfony/maker-bundle               v1.14.3 v1.14.6 Symfony Maker helps you c...
symfony/mime                       v4.3.9  v4.3.11 A library to manipulate M...
symfony/monolog-bridge             v4.3.9  v4.3.11 Symfony Monolog Bridge
symfony/monolog-bundle             v3.5.0  v3.5.0  Symfony MonologBundle
symfony/options-resolver           v4.3.9  v4.3.11 Symfony OptionsResolver C...
symfony/orm-pack                   v1.0.7  v1.0.8  A pack for the Doctrine ORM
symfony/phpunit-bridge             v5.0.2  v5.0.7  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu          v1.13.1 v1.15.0 Symfony polyfill for intl...
symfony/polyfill-intl-idn          v1.13.1 v1.15.0 Symfony polyfill for intl...
symfony/polyfill-mbstring          v1.13.1 v1.15.0 Symfony polyfill for the ...
symfony/polyfill-php72             v1.13.1 v1.15.0 Symfony polyfill backport...
symfony/polyfill-php73             v1.13.1 v1.15.0 Symfony polyfill backport...
symfony/process                    v4.3.9  v4.3.11 Symfony Process Component
symfony/profiler-pack              v1.0.4  v1.0.4  A pack for the Symfony we...
symfony/property-access            v4.3.9  v4.3.11 Symfony PropertyAccess Co...
symfony/property-info              v4.3.9  v4.3.11 Symfony Property Info Com...
symfony/routing                    v4.3.9  v4.3.11 Symfony Routing Component
symfony/security-acl               v3.0.4  v3.0.4  Symfony Security Componen...
symfony/security-bundle            v4.3.9  v4.3.11 Symfony SecurityBundle
symfony/security-core              v4.3.9  v4.3.11 Symfony Security Componen...
symfony/security-csrf              v4.3.9  v4.3.11 Symfony Security Componen...
symfony/security-guard             v4.3.9  v4.3.11 Symfony Security Componen...
symfony/security-http              v4.3.9  v4.3.11 Symfony Security Componen...
symfony/serializer                 v4.3.9  v4.3.11 Symfony Serializer Component
symfony/serializer-pack            v1.0.2  v1.0.3  A pack for the Symfony se...
symfony/service-contracts          v1.1.8  v2.0.1  Generic abstractions rela...
symfony/stopwatch                  v4.3.9  v4.3.11 Symfony Stopwatch Component
symfony/swiftmailer-bundle         v3.4.0  v3.4.0  Symfony SwiftmailerBundle
symfony/templating                 v4.3.9  v4.3.11 Symfony Templating Component
symfony/test-pack                  v1.0.6  v1.0.6  A pack for functional and...
symfony/translation                v4.3.9  v4.3.11 Symfony Translation Compo...
symfony/translation-contracts      v1.1.7  v2.0.1  Generic abstractions rela...
symfony/twig-bridge                v4.3.9  v4.3.11 Symfony Twig Bridge
symfony/twig-bundle                v4.3.9  v4.3.11 Symfony TwigBundle
symfony/twig-pack                  v1.0.0  v1.0.0  A Twig pack for Symfony p...
symfony/validator                  v4.3.9  v4.3.11 Symfony Validator Component
symfony/var-dumper                 v4.3.9  v4.3.11 Symfony mechanism for exp...
symfony/var-exporter               v4.3.9  v4.3.11 A blend of var_export() +...
symfony/web-link                   v4.3.9  v4.3.11 Symfony WebLink Component
symfony/web-profiler-bundle        v4.3.9  v4.3.11 Symfony WebProfilerBundle
symfony/web-server-bundle          v4.3.9  v4.3.11 Symfony WebServerBundle
symfony/yaml                       v4.3.9  v4.3.11 Symfony Yaml Component
`

**PHP version**

`-sh-4.2$ php -v
PHP 7.2.25 (cli) (built: Nov 20 2019 17:44:37) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.25, Copyright (c) 1999-2018, by Zend Technologies`


and about the error message yes, it is appearing on the normal screen and without detailed information about error file and number, might be sonata admin or page bundle default template.

If you want more information please let me know I will post here.

Many Thanks @VincentLanglet

**Comment by wwtvishal** [comment]
Hi @VincentLanglet 

Please help me with your feedback.

Many Thanks!
