### ISSUE TITLE
Declaration of SharedBlockBlockService::validateBlock must be compatible with AbstractAdminBlockService::validateBlock

### ISSUE THREAD

**Issue by tkAlexander** [sonata-project/SonataPageBundle#1168]
#829 Declaration of SharedBlockBlockService::validateBlock must be compatible with AbstractAdminBlockService::validateBlock

# Environment

#### Sonata packages

```
sonata-project/admin-bundle              3.63.0 3.70.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.20.0 3.20.0 Symfony SonataBlockBundle
sonata-project/cache                     1.1.1  2.0.1  Cache library
sonata-project/cache-bundle              2.4.2  3.2.1  This bundle provides caching services
sonata-project/classification-bundle     3.12.1 3.12.1 Symfony SonataClassificationBundle
sonata-project/core-bundle               3.20.0 3.20.0 Symfony SonataCoreBundle (abandoned)
sonata-project/datagrid-bundle           2.5.0  3.2.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.6.0  1.6.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.18.0 3.18.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  2.2.0  2.2.0  Lightweight Exporter library
sonata-project/form-extensions           0.1.2  1.4.0  Symfony form extensions
sonata-project/formatter-bundle          4.2.0  4.2.0  Symfony SonataFormatterBundle
sonata-project/intl-bundle               2.7.0  2.7.0  Symfony SonataIntlBundle
sonata-project/media-bundle              3.25.0 3.25.0 Symfony SonataMediaBundle
sonata-project/notification-bundle       3.4.0  3.7.0  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.17.3 3.17.3 This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.10.0 2.10.0 Symfony SonataSeoBundle
sonata-project/translation-bundle        2.5.0  2.5.0  SonataTranslationBundle
sonata-project/twig-extensions           0.1.1  1.3.0  Sonata twig extensions
sonata-project/user-bundle               4.5.3  4.5.3  Symfony SonataUserBundle
```

#### Symfony packages

```
symfony/asset                      v4.4.10 v4.4.10 Symfony Asset Component
symfony/browser-kit                v4.4.10 v4.4.10 Symfony BrowserKit Component
symfony/cache                      v4.4.10 v4.4.10 Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts            v1.1.7  v1.1.7  Generic abstractions related to caching
symfony/class-loader               v3.4.42 v3.4.42 Symfony ClassLoader Component
symfony/config                     v4.4.10 v4.4.10 Symfony Config Component
symfony/console                    v4.4.10 v4.4.10 Symfony Console Component
symfony/css-selector               v4.4.10 v4.4.10 Symfony CssSelector Component
symfony/debug                      v4.4.10 v4.4.10 Symfony Debug Component
symfony/debug-bundle               v4.4.10 v4.4.10 Symfony DebugBundle
symfony/dependency-injection       v4.4.10 v4.4.10 Symfony DependencyInjection Component
symfony/doctrine-bridge            v4.4.10 v4.4.10 Symfony Doctrine Bridge
symfony/dom-crawler                v4.4.10 v4.4.10 Symfony DomCrawler Component
symfony/dotenv                     v4.4.10 v4.4.10 Registers environment variables from a .env file
symfony/error-handler              v4.4.10 v4.4.10 Symfony ErrorHandler Component
symfony/event-dispatcher           v4.4.10 v4.4.10 Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v1.1.7  v1.1.7  Generic abstractions related to dispatching event
symfony/expression-language        v4.4.10 v4.4.10 Symfony ExpressionLanguage Component
symfony/filesystem                 v4.4.10 v4.4.10 Symfony Filesystem Component
symfony/finder                     v4.4.10 v4.4.10 Symfony Finder Component
symfony/flex                       v1.8.4  v1.8.4  Composer plugin for Symfony
symfony/form                       v4.4.10 v4.4.10 Symfony Form Component
symfony/framework-bundle           v4.4.10 v4.4.10 Symfony FrameworkBundle
symfony/http-foundation            v4.4.10 v4.4.10 Symfony HttpFoundation Component
symfony/http-kernel                v4.4.10 v4.4.10 Symfony HttpKernel Component
symfony/inflector                  v4.4.10 v4.4.10 Symfony Inflector Component
symfony/intl                       v4.4.10 v4.4.10 A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/lock                       v4.4.10 v4.4.10 Symfony Lock Component
symfony/mailchimp-mailer           v4.4.10 v4.4.10 Symfony Mailchimp Mailer Bridge
symfony/mailer                     v4.4.10 v4.4.10 Symfony Mailer Component
symfony/maker-bundle               v1.19.0 v1.19.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                  v4.4.10 v4.4.10 Symfony Messenger Component
symfony/mime                       v4.4.10 v4.4.10 A library to manipulate MIME messages
symfony/monolog-bridge             v4.4.10 v4.4.10 Symfony Monolog Bridge
symfony/monolog-bundle             v3.5.0  v3.5.0  Symfony MonologBundle
symfony/options-resolver           v4.4.10 v4.4.10 Symfony OptionsResolver Component
symfony/phpunit-bridge             v5.1.2  v5.1.2  Symfony PHPUnit Bridge
symfony/polyfill-ctype             v1.17.1 v1.17.1 Symfony polyfill for ctype functions
symfony/polyfill-iconv             v1.17.1 v1.17.1 Symfony polyfill for the Iconv extension
symfony/polyfill-intl-icu          v1.17.1 v1.17.1 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.17.1 v1.17.1 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring          v1.17.1 v1.17.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.17.0 v1.17.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.17.1 v1.17.1 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.17.1 v1.17.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                    v4.4.10 v4.4.10 Symfony Process Component
symfony/property-access            v4.4.10 v4.4.10 Symfony PropertyAccess Component
symfony/proxy-manager-bridge       v4.4.10 v4.4.10 Symfony ProxyManager Bridge
symfony/requirements-checker       v1.1.5  v1.1.5  Check Symfony requirements and give recommendations
symfony/routing                    v4.4.10 v4.4.10 Symfony Routing Component
symfony/security                   v4.4.10 v4.4.10 Symfony Security Component
symfony/security-acl               v3.0.4  v3.0.4  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.4.10 v4.4.10 Symfony SecurityBundle
symfony/serializer                 v4.4.10 v4.4.10 Symfony Serializer Component
symfony/service-contracts          v1.1.8  v1.1.8  Generic abstractions related to writing services
symfony/stopwatch                  v4.4.10 v4.4.10 Symfony Stopwatch Component
symfony/swiftmailer-bundle         v3.4.0  v3.4.0  Symfony SwiftmailerBundle
symfony/templating                 v4.4.10 v4.4.10 Symfony Templating Component
symfony/translation                v4.4.10 v4.4.10 Symfony Translation Component
symfony/translation-contracts      v1.1.7  v1.1.7  Generic abstractions related to translation
symfony/twig-bridge                v4.4.10 v4.4.10 Symfony Twig Bridge
symfony/twig-bundle                v4.4.10 v4.4.10 Symfony TwigBundle
symfony/validator                  v4.4.10 v4.4.10 Symfony Validator Component
symfony/var-dumper                 v4.4.10 v4.4.10 Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter               v4.4.10 v4.4.10 A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-profiler-bundle        v4.4.10 v4.4.10 Symfony WebProfilerBundle
symfony/webpack-encore-bundle      v1.7.3  v1.7.3  Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v4.4.10 v4.4.10 Symfony Yaml Component

```

#### PHP version

```
PHP 7.3.16 (cli) (built: Mar 27 2020 17:33:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.16, Copyright (c) 1998-2018 Zend Technologies
```

## Subject

Declaration of Sonata\PageBundle\Block\SharedBlockBlockService::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) must be compatible with Sonata\BlockBundle\Block\Service\AbstractAdminBlockService::validateBlock(Sonata\Form\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block)

## Steps to reproduce

```
php bin/console
```

## Actual results

```
PHP Fatal error:  Declaration of Sonata\PageBundle\Block\SharedBlockBlockService::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) must be compatible with Sonata\BlockBundle\Block\Service\AbstractAdminBlockService::validateBlock(Sonata\Form\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) in /var/www/html/vendor/sonata-project/page-bundle/src/Block/SharedBlockBlockService.php on line 177
Symfony\Component\ErrorHandler\Error\FatalError^ {#9275
  -error: array:4 [
    "type" => 64
    "message" => "Declaration of Sonata\PageBundle\Block\SharedBlockBlockService::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) must be compatible with Sonata\BlockBundle\Block\Service\AbstractAdminBlockService::validateBlock(Sonata\Form\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block)"
    "file" => "/var/www/html/vendor/sonata-project/page-bundle/src/Block/SharedBlockBlockService.php"
    "line" => 177
  ]
  #message: "Compile Error: Declaration of Sonata\PageBundle\Block\SharedBlockBlockService::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) must be compatible with Sonata\BlockBundle\Block\Service\AbstractAdminBlockService::validateBlock(Sonata\Form\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block)"
  #code: 0
  #file: "./vendor/sonata-project/page-bundle/src/Block/SharedBlockBlockService.php"
  #line: 177
}
```

**Comment by tonyellow** [comment]
having the exact same problem!

**Comment by wbloszyk** [comment]
@tkAlexander @tonyellow Can you check this change by use `"sonata-project/form-extensions": "0.x-dev as 0.1.3"`?
https://github.com/sonata-project/form-extensions/commit/d8bc00913d2b63ee39a25f668a912c59d68f3732

This should fix this error, if it work then @greg0ire can release it.

**Comment by tonyellow** [comment]
@wbloszyk I don't see sonata-project/form-extensions in my composer

**Comment by jordisala1991** [comment]
Then, you should add the requirement to see if a new release of that dependency could fix the issue

**Comment by wbloszyk** [comment]
@tonyellow You don't have it in your composer but composer install it as other package/bundles dependencies. Check it by:
```
composer show sonata-project/*
```

**Comment by tonyellow** [comment]
ok @wbloszyk thanks for sharing, didnt know this. I would really like to help out but how can i change the version of this package while it is not in my composer.json?

**Comment by wbloszyk** [comment]
@tonyellow  just add `"sonata-project/form-extensions": "0.x-dev as 0.1.3"` to yours composer in `require` section and run:
```
composer update
```

**Comment by tonyellow** [comment]
I fixed the block bundle to 3.20 and added the dependancy for form-extensioons. Then i run composer update having the exact same error again:


Here is my updated composer.json:

{
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "api-platform/api-pack": "^1.1",
        "doctrine/doctrine-bundle": "^1.0",
        "doctrine/doctrine-fixtures-bundle": "^3.3",
        "doctrine/doctrine-migrations-bundle": "^2.0",
        "endroid/qr-code-bundle": "^3.4",
        "friendsofsymfony/ckeditor-bundle": "1.2.0",
        "friendsofsymfony/elastica-bundle": "^5.1",
        "friendsofsymfony/rest-bundle": "^2.6",
        "google/apiclient": "^2.4",
        "guzzlehttp/guzzle": "^6.3",
        "jms/translation-bundle": "^1.4",
        "knplabs/knp-gaufrette-bundle": "^0.7.0",
        "knplabs/knp-snappy-bundle": "^1.6",
        "lcobucci/jwt": "^3.3",
        "lexik/jwt-authentication-bundle": "^2.7",
        "liip/imagine-bundle": "^2.2",
        "misd/phone-number-bundle": "^1.3",
        "oneup/uploader-bundle": "^2.1",
        "opsway/doctrine-dbal-postgresql": "^0.8.1",
        "payum/offline": "^1.5",
        "payum/payum-bundle": "^2.3",
        "php-http/guzzle6-adapter": "^2.0",
        "pixassociates/sortable-behavior-bundle": "^1.5",
        "portphp/portphp": "^1.4",
        "portphp/steps": "^1.2",
        "ramsey/uuid-doctrine": "^1.5",
        "simplethings/entity-audit-bundle": "^1.0",
        "sonata-project/admin-bundle": "^3.56",
        "sonata-project/block-bundle": "3.20",
        "sonata-project/cache-bundle": "^2.4",
        "sonata-project/doctrine-orm-admin-bundle": "^3.12",
        "sonata-project/easy-extends-bundle": "^2.5",
        "sonata-project/formatter-bundle": "^4.1",
        "sonata-project/google-authenticator": "^2.2",
        "sonata-project/intl-bundle": "^2.7",
        "sonata-project/notification-bundle": "^3.6",
        "sonata-project/notification-orm-pack": "^1.0",
        "sonata-project/page-bundle": "^3.13",
        "sonata-project/seo-bundle": "^2.9",
        "sonata-project/translation-bundle": "^2.4",
        "sonata-project/user-bundle": "^4.5",
        "stof/doctrine-extensions-bundle": "^1.3",
        "symfony/console": "4.3.*",
        "symfony/debug-bundle": "4.3.*",
        "symfony/dotenv": "4.3.*",
        "symfony/flex": "^1.1",
        "symfony/framework-bundle": "4.3.*",
        "symfony/maker-bundle": "^1.14",
        "symfony/mercure-bundle": "^0.2",
        "symfony/security-bundle": "4.3.*",
        "symfony/swiftmailer-bundle": "^3.4",
        "symfony/yaml": "4.3.*",
        "twig/markdown-extra": "^3.0",
        "webonyx/graphql-php": "^0.13.8",
        "whiteoctober/tcpdf-bundle": "^1.1",
        "yokai/sonata-workflow": "^0.2.0",
        "sonata-project/form-extensions": "0.x-dev as 0.1.3"
    },
    "require-dev": {
        "api-platform/schema-generator": "^2.1",
        "symfony/profiler-pack": "^1.0",
        "symfony/var-dumper": "4.3.*"
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php56": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php71": "*"
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "extra": {
        "symfony": {
            "allow-contrib": "true",
            "require": "4.3.*"
        }
    }
}

**Comment by wbloszyk** [comment]
Can you do it:
    ```
    $ composer show --latest 'sonata-project/*'
    # Put the result here.
    ```

**Comment by tonyellow** [comment]
```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.68.0          3.71.1             The missing Symfony Admin Generator
sonata-project/block-bundle              3.20.0          4.2.0              Symfony SonataBlockBundle
sonata-project/cache                     1.1.1           2.0.1              Cache library
sonata-project/cache-bundle              2.4.2           3.2.1              This bundle provides caching services
sonata-project/core-bundle               3.20.0          3.20.0             Symfony SonataCoreBundle (abandoned)
sonata-project/datagrid-bundle           2.5.0           3.2.0              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.7.0           1.7.0              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.13.0          3.20.0             Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0           2.5.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  2.2.0           2.2.0              Lightweight Exporter library
sonata-project/form-extensions           0.x-dev d8bc009 dev-master 7dcd306 Symfony form extensions
sonata-project/formatter-bundle          4.2.0           4.2.0              Symfony SonataFormatterBundle
sonata-project/google-authenticator      2.2.0           2.2.0              Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.7.0           2.7.0              Symfony SonataIntlBundle
sonata-project/notification-bundle       3.6.2           3.8.0              Symfony SonataNotificationBundle
sonata-project/notification-orm-pack     1.0.0           1.0.0              A pack for SonataNotificationBundle with ORM support
sonata-project/page-bundle               3.17.3          3.18.0             This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.10.0          2.11.0             Symfony SonataSeoBundle
sonata-project/translation-bundle        2.5.0           2.5.0              SonataTranslationBundle
sonata-project/twig-extensions           0.1.1           1.3.1              Sonata twig extensions
sonata-project/user-bundle               4.5.3           4.6.0              Symfony SonataUserBundle```

```
$ composer show --latest 'symfony/*'
Restricting packages listed in "symfony/symfony" to "4.3.*"
symfony/asset                      v4.3.11 v4.3.11 Symfony Asset Component
symfony/cache                      v4.3.11 v4.3.11 Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts            v1.1.9  v2.1.3  Generic abstractions related to caching
symfony/config                     v4.3.11 v4.3.11 Symfony Config Component
symfony/console                    v4.3.11 v4.3.11 Symfony Console Component
symfony/debug                      v4.3.11 v4.3.11 Symfony Debug Component
symfony/debug-bundle               v4.3.11 v4.3.11 Symfony DebugBundle
symfony/dependency-injection       v4.3.11 v4.3.11 Symfony DependencyInjection Component
symfony/deprecation-contracts      v2.1.3  v2.1.3  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v4.3.11 v4.3.11 Symfony Doctrine Bridge
symfony/dotenv                     v4.3.11 v4.3.11 Registers environment variables from a .env file
symfony/event-dispatcher           v4.3.11 v4.3.11 Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v1.1.9  v2.1.3  Generic abstractions related to dispatching event
symfony/expression-language        v4.3.11 v4.3.11 Symfony ExpressionLanguage Component
symfony/filesystem                 v4.3.11 v4.3.11 Symfony Filesystem Component
symfony/finder                     v4.3.11 v4.3.11 Symfony Finder Component
symfony/flex                       v1.8.4  v1.8.4  Composer plugin for Symfony
symfony/form                       v4.3.11 v4.3.11 Symfony Form Component
symfony/framework-bundle           v4.3.11 v4.3.11 Symfony FrameworkBundle
symfony/http-client                v4.3.11 v4.3.11 Symfony HttpClient component
symfony/http-client-contracts      v1.1.9  v2.1.3  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.3.11 v4.3.11 Symfony HttpFoundation Component
symfony/http-kernel                v4.3.11 v4.3.11 Symfony HttpKernel Component
symfony/inflector                  v4.3.11 v4.3.11 Symfony Inflector Component
symfony/intl                       v4.3.11 v4.3.11 A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle               v1.19.0 v1.19.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mercure                    v0.4.0  v0.4.0  Symfony Mercure Component
symfony/mercure-bundle             v0.2.5  v0.2.5  Symfony MercureBundle
symfony/mime                       v4.3.11 v4.3.11 A library to manipulate MIME messages
symfony/options-resolver           v4.3.11 v4.3.11 Symfony OptionsResolver Component
symfony/polyfill-intl-grapheme     v1.17.1 v1.17.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.17.1 v1.17.1 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.17.1 v1.17.1 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.17.1 v1.17.1 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.17.1 v1.17.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.17.0 v1.17.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.17.1 v1.17.1 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.17.1 v1.17.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                    v4.3.11 v4.3.11 Symfony Process Component
symfony/profiler-pack              v1.0.4  v1.0.4  A pack for the Symfony web profiler
symfony/property-access            v4.3.11 v4.3.11 Symfony PropertyAccess Component
symfony/property-info              v4.3.11 v4.3.11 Symfony Property Info Component
symfony/routing                    v4.3.11 v4.3.11 Symfony Routing Component
symfony/security-acl               v3.0.4  v3.0.4  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.3.11 v4.3.11 Symfony SecurityBundle
symfony/security-core              v4.3.11 v4.3.11 Symfony Security Component - Core Library
symfony/security-csrf              v4.3.11 v4.3.11 Symfony Security Component - CSRF Library
symfony/security-guard             v4.3.11 v4.3.11 Symfony Security Component - Guard
symfony/security-http              v4.3.11 v4.3.11 Symfony Security Component - HTTP Integration
symfony/serializer                 v4.3.11 v4.3.11 Symfony Serializer Component
symfony/service-contracts          v1.1.9  v2.1.3  Generic abstractions related to writing services
symfony/stopwatch                  v4.3.11 v4.3.11 Symfony Stopwatch Component
symfony/string                     v5.1.2  v5.1.2  Symfony String component
symfony/swiftmailer-bundle         v3.4.0  v3.4.0  Symfony SwiftmailerBundle
symfony/templating                 v4.3.11 v4.3.11 Symfony Templating Component
symfony/translation                v4.3.11 v4.3.11 Symfony Translation Component
symfony/translation-contracts      v1.1.9  v2.1.3  Generic abstractions related to translation
symfony/twig-bridge                v4.3.11 v4.3.11 Symfony Twig Bridge
symfony/twig-bundle                v4.3.11 v4.3.11 Symfony TwigBundle
symfony/validator                  v4.3.11 v4.3.11 Symfony Validator Component
symfony/var-dumper                 v4.3.11 v4.3.11 Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter               v4.3.11 v4.3.11 A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                   v4.3.11 v4.3.11 Symfony WebLink Component
symfony/web-profiler-bundle        v4.3.11 v4.3.11 Symfony WebProfilerBundle
symfony/workflow                   v4.3.11 v4.3.11 Symfony Workflow Component
symfony/yaml                       v4.3.11 v4.3.11 Symfony Yaml Component
```

```
$ php -v
PHP 7.3.17 (cli) (built: Apr 24 2020 18:17:51) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.17, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.17, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by wbloszyk** [comment]
@tonyellow Upgrade symfony to 4.4 by:
```
"extra": {
    "symfony": {
        "allow-contrib": "true",
        "require": "4.3." <- change this to 4.4 
     }
}
and
    "symfony/security-bundle": "4.3.", 
to
    "symfony/security-bundle": "^4.4", 
for all symfony/* 
```

This will allow upgrade this package (remove form-extensions in composer before): 
> ```
> sonata-project/admin-bundle              3.68.0          3.71.1             The missing Symfony Admin Generator
> sonata-project/doctrine-orm-admin-bundle 3.13.0          3.20.0             Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
> sonata-project/notification-bundle       3.6.2           3.8.0              Symfony SonataNotificationBundle
> sonata-project/page-bundle               3.17.3          3.18.0             This bundle provides a Site and Page management through container and block services
> sonata-project/seo-bundle                2.10.0          2.11.0             Symfony SonataSeoBundle
> sonata-project/user-bundle               4.5.3           4.6.0              Symfony SonataUserBundle```
> ```

Then core-bundle will not be installed and *-extensions will be upgrade to 1.x
> ```
> sonata-project/core-bundle               3.20.0          3.20.0             Symfony SonataCoreBundle (abandoned)
> sonata-project/form-extensions           0.x-dev d8bc009 dev-master 7dcd306 Symfony form extensions
> sonata-project/twig-extensions           0.1.1           1.3.1              Sonata twig extensions
> ```

register this extensions in config/bundles.php:
```
    Sonata\Form\Bridge\Symfony\SonataFormBundle::class => ['all' => true],
    Sonata\Twig\Bridge\Symfony\SonataTwigBundle::class => ['all' => true],
```

**Comment by tonyellow** [comment]
@wbloszyk Sorry for the delay. I did all this but it results in a new error:

The service "twig" has a dependency on a non-existent service "sonata.doctrine.model.adapter.chain".

**Comment by tonyellow** [comment]
> i

Resolved it by adding:     Sonata\Doctrine\Bridge\Symfony\Bundle\SonataDoctrineBundle::class => ['all' => true],

**Comment by tonyellow** [comment]
Now more errors, Could not load type "Sonata\CoreBundle\Form\Type\DateRangePickerType": class does not exist.
I guess these files have moved. Let me see when I am at the office if I can easily resolve this. Seems like a lot of work has been done on Sonata, awesome ofcourse!

**Comment by tonyellow** [comment]
I resolved all error regarding flash messages and forms by following the advices here: https://github.com/sonata-project/SonataAdminBundle/issues/6173

Thanks for all the great work!

**Comment by wbloszyk** [comment]
@tonyellow Some time ago I drop CoreBundle in whole Sonata 3 becouse it is deprecated bundle. You are using some Sonata 3 bundles where CoreBundle is require and some bundle where it is not. You have 3 option to resolve it:
- upgrade Symfony to 4.4 then dependencies will not be require CoreBundle
    - doctrine, form, twig -extensions must register in `config/bundles.php`
- dont upgrade Symfony and use CoreBundle 3.20 
    - CoreBundle and doctrine-extensions must be register
    - form and twig -extensions can be register optional
    - form-extensions should be in 0.x-dev
- set `"sonata-project/core-bundle": "3.19.2" and `composer update` to download bundles before this change

**Comment by tonyellow** [comment]
@wbloszyk I'm currently on Symfony 4.4.10 by folowing all your advices in this topic. I removed all references to the CoreBundle in my project and loaded the extensions in config/bundles.php. Everyhting works.

**Comment by VincentLanglet** [comment]
We just need to release 0.1.3 of form extension to close this @wbloszyk ?

**Comment by VincentLanglet** [comment]
> @tkAlexander @tonyellow Can you check this change by use `"sonata-project/form-extensions": "0.x-dev as 0.1.3"`?
> [sonata-project/form-extensions@d8bc009](https://github.com/sonata-project/form-extensions/commit/d8bc00913d2b63ee39a25f668a912c59d68f3732)
> 
> This should fix this error, if it work then @greg0ire can release it.

Isn't this already release as 0.1.2 ?

**Comment by wbloszyk** [comment]
@VincentLanglet I forgot about changelog in 0.x it not and should not be updated.
