### ISSUE TITLE
Remove oppressive words from code

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataPageBundle#1174]
## Feature Request

We should avoid terms like *blacklist*, *whitliste, *master*, *slave*, ... and use more tech-related words like *blocklist*, *prmary*, *secondary*,...

In this repo, we use the term *whitelist* which could be replaced with *allowlist*:
https://github.com/sonata-project/SonataPageBundle/blob/3.x/assets/src/js/composer.js#L787
https://github.com/sonata-project/SonataPageBundle/blob/3.x/src/Resources/views/PageAdmin/compose.html.twig#L57

**Comment by OmAshish** [comment]
Hi core23! I would like to contribute in this! Can I get the task? 😃

**Comment by core23** [comment]
There's already an open PR https://github.com/sonata-project/SonataPageBundle/pull/1209. Maybe you can help to get this done.
