### ISSUE TITLE
Remove coupling to NotificationBundle

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataPageBundle#1238]
## Feature Request

This is the last bundle that relies on the [SonataNotificationBundle](https://github.com/sonata-project/SonataNotificationBundle/) for no good reason. The original idea was to allow async snapshot creation / cleanup. This can also be done via commands and shouldn't take too long for a normal number of pages.

To allow deprecating the usage, we could introduce a new `SnapshotManagerInterface` with two methods `createSnapshotsForSite` and `cleanupSnashotsForSite`.

WDYT @sonata-project/contributors

**Comment by VincentLanglet** [comment]
I'll close this in favor of https://github.com/sonata-project/SonataPageBundle/issues/1415
