### ISSUE TITLE
Add EventDispatcher after create a snapshot 

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataPageBundle#1317]
## Add EventDispatcher after update or create an snapshot 

after create  a snapshot I will dispatch an event to be able create listeners for who implement this lib.

e.g:
```php
class SonataPageEvent
{
    public const CREATE_SNAPSHOT = 'sonata.page.create_snapshot';

    private $page;

    public function __construct(PageInterface $page)
    {
        $this->page = $page;
    }

    public function getPage(): PageInterface
    {
        return $this->page;
    }
}
```

```php
$event = new SonataPageEvent($page);
$dispatcher->dispatch($event, SonataPageEvent::CREATE);
```

I'll put this after this line
https://github.com/sonata-project/SonataPageBundle/blob/3.x/src/Controller/SnapshotAdminController.php#L67

**Comment by eerison** [comment]
let me know if does it make sense, if yes I'll open a Pull request :)

**Comment by VincentLanglet** [comment]
There is already the call `$this->admin->create($snapshot);`

Wouldn't it better to create an AdminExtension to dispatch action after every action create/edit/...
The AdminExtension could be here: https://github.com/sonata-project/SonataAdminBundle/tree/3.x/src/Admin/Extension
And then the SnapShot admin could use this admin extension.

**Comment by eerison** [comment]
@VincentLanglet 
Hmmm I don't fully understand how it works.

could you give any example?

**Comment by VincentLanglet** [comment]
If we're doing something like https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Admin/Extension/LockExtension.php

Implementing all the PostCreate, PostUpdate, PostDelete, etc methods and dispatching an event inside.

Then, the admin class will call these method https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Admin/AbstractAdmin.php#L616 if the Extension is added to the admin.
