### ISSUE TITLE
Documentation: How to use symfony action page

### ISSUE THREAD

**Issue by haivala** [sonata-project/SonataPageBundle#1368]
## Feature Request

It is not mentioned anywhere how one should get the current cms page in symfony action page controller

**Comment by haivala** [comment]
What I'm doing now is
```
use Sonata\PageBundle\CmsManager\CmsManagerSelector;

class DashboardController extends AbstractController
{
    public function index(Request $request, CmsManagerSelector $cms): Response
    {
        $page = $cms->retrieve()->getCurrentPage();
        return $this->render('dashboard/index.html.twig', [
            'page' => $page,
        ]);
    }
}
```
And this does not work with internationalized routing: https://github.com/sonata-project/SonataPageBundle/issues/1367

**Comment by haivala** [comment]
I think this should not be closed..

**Comment by mesiarm** [comment]
> ## Feature Request
> It is not mentioned anywhere how one should get the current cms page in symfony action page controller

Does Internationalized routing solves your problem? https://symfony.com/blog/new-in-symfony-4-1-internationalized-routing
