### ISSUE TITLE
Symfony 5 and 6 support

### ISSUE THREAD

**Issue by dunglas** [sonata-project/SonataPageBundle#1410]
## Feature Request

The bundle does not currently support recent versions of Symfony. Symfony 4 will not be maintained anymore in November. Is there a plan to make this bundle compatible with recent versions?

**Comment by jordisala1991** [comment]
Hi! At this moment we are finishing the upgrade for SonataUserBundle, we have two more bundles missing an upgrade: SonataFormatterBundle and SonataPageBundle.

Sadly we are currently not a lot of people maintaining Sonata and we have to focus our efforts on the most used bundles.

We have another problem for this particular bundle. None of the current maintainers have ever used it.

Do you use this bundle? Do you have time to help us upgrading it?

**Comment by VincentLanglet** [comment]
Btw, our todo list for all the sonata bundle can be found here https://github.com/sonata-project/dev-kit/issues/1715

**Comment by kursez** [comment]
How can I get in contact with the people that are helping making this happen, I want to contribute

**Comment by greg0ire** [comment]
@kursez I would recommend #sonata on [the symfony-devs slack](https://symfony.com/slack-invite).

**Comment by VincentLanglet** [comment]
We can use this issue to discuss about what to do @kursez.
@jordisala1991 and I can help you about the changes needed.

To be able to support SF5/6, we'll have to drop the following bundle:
- SonataNotificationBundle
- SonataCacheBundle

The first one need to be replaced by the Symfony messenger component, the second one by the Symfony cache.

But the first step could be, on the 4.x branch of SonataPageBundle to bump the version in the composer.json
https://github.com/sonata-project/SonataPageBundle/blob/3.x/composer.json#L28-L38
to use SonataAdmin 4 and SonataBlock 4 and then update all the code in this bundle to make it work.

**Comment by mareckigit** [comment]
Have you started work on the new version yet?

**Comment by VincentLanglet** [comment]
> Have you started work on the new version yet?

I don't think anybody started, so feel free to provide a PR.

**Comment by Haniki** [comment]
Hi, I tried that on my own, it should be working with SF4. 
I won't have time to continue this, and I'm not sure to understand enough this project to make it the right way.

Anyways I've made a pull request in case it might help. Feel free to improve my code or delete that PR if it is not what it supposed to be like.

**Comment by mareckigit** [comment]
@VincentLanglet What do you mean by drop SonataCacheBundle? Basically, I don't see the need to use an ESI / SSI / JS ASYNC cache for blocks. Blocks can be saved in the Symfony cache like Redis and this is part of the Block Bundle.

**Comment by VincentLanglet** [comment]
> @VincentLanglet What do you mean by drop SonataCacheBundle? Basically, I don't see the need to use an ESI / SSI / JS ASYNC cache for blocks. Blocks can be saved in the Symfony cache like Redis and this is part of the Block Bundle.

Those dependency need to be removed https://github.com/sonata-project/SonataPageBundle/blob/3.x/composer.json#L30-L31 because they are not maintained anymore.

I don't know why they are currently used ; but either the feature must be removed, either it must be migrated to something else like symfony cache.

**Comment by mareckigit** [comment]
I understand why they should be removed, but don't see the need to replace them. I'm going to prepare fork to build the version without SonataCacheBundle and SonataNotificationBundle. My goal is compatibility with SF 5.4 and PHP 8.0.

@Haniki the current official release 3.x works with SF 4.4

**Comment by VincentLanglet** [comment]
> @Haniki the current official release 3.x works with SF 4.4

he meants SF5/6

**Comment by eerison** [comment]
I saw your MR @Haniki, But it's quite big 😄 

@mareckigit @kursez and @Haniki (in case you find some time for this 😃 )

what do you think to create small Pull requests and we going to merge this into `4.x` branch?

because to review a PR with all stuffs are quite hard I guess!

we could open different PR for example:

-  #1415 
- #1096
- #1416 
- #1417 
- Add compatibly Symfony 6

the idea is just create small PR and the others can work in different parts, I want to help too, but I need to know what exactly you are working on and what you have done!

Or do you think is it better to be handled by one person only?

cc @VincentLanglet

**Comment by VincentLanglet** [comment]
> cc @VincentLanglet

I agree it will be easier to review.

he said that he won't have time to continue this, so
- either someone finish the PR
- either we merge it like this and then people try separate fix
- either people open smaller PR helped by this big one (preferred solution)

**Comment by eerison** [comment]
> I saw your MR @Haniki, But it's quite big 😄
> 
> @mareckigit @kursez and @Haniki (in case you find some time for this 😃 )
> 
> what do you think to create small Pull requests and we going to merge this into `4.x` branch?
> 
> because to review a PR with all stuffs are quite hard I guess!
> 
> we could open different PR for example:
> 
> * [ ]  remove SonataNotificationBundle
> * [ ]  remove SonataCacheBundle
> * [ ]  Add compatibly with Symfony 5
> * [ ]  Remove deprecated code
> * [ ]  Add compatibly Symfony 6
> 
> the idea is just create small PR and the others can work in different parts, I want to help too, but I need to know what exactly you are working on and what you have done!
> 
> Or do you think is it better to be handled by one person only?
> 
> cc @VincentLanglet

Ok, I'll take this as a start

I will do the `remove SonataNotificationBundle` 😃

**Comment by axio-vincent** [comment]
> @kursez I would recommend #sonata on [the symfony-devs slack](https://symfony.com/slack-invite).

Hello

Where is the #sonata ???

![image](https://user-images.githubusercontent.com/92991259/167626265-2caa496a-44d7-492d-ae9d-3569746c7ef2.png)

**Comment by mesiarm** [comment]
What is missing to Symfony 5 and 6 support?

**Comment by eerison** [comment]
> What is missing to Symfony 5 and 6 support?

Hi @mesiarm we're trying to keep the issues listed in this ticket #1416 and [4.0 milestone](https://github.com/sonata-project/SonataPageBundle/milestone/1) , our main priority is support `Symfony 5` and `sonata 4` first.

there you can see the tickets that are missing, But we are more or less stuck in this ticket: #1417

really soon we hope to finish this ticket, and we can start the others, But until there if you want to test the branch `4.x` and see if you can find some issue, fell free.

**Comment by VincentLanglet** [comment]
This will be close by https://github.com/sonata-project/SonataPageBundle/pull/1491
