### ISSUE TITLE
after create a new snapshot, it goes for page edit, and should back to the list

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataPageBundle#1453]
after create a new snapshot, it goes for page edit, and should back to the list

**Comment by mesiarm** [comment]
Maybe it could be simplified - add another button in edit page to update and create snapshot with one click.

**Comment by eerison** [comment]
> Maybe it could be simplified - add another button in edit page to update and create snapshot with one click.

In dev environment it already happen, but if we do this in prod, no make sense maintain the snapshot

**Comment by eerison** [comment]
And IMO we should keep the snapshot feature as it's!

**Comment by haivala** [comment]
I would say that snapshots should be able to be timed in prod so that when time comes another content would be shown to users that are not logged in.

I have used them like this: edit content -> make publication -> edit content again and make new snapshot -> then edit times of the snapshots in question.

**Comment by eerison** [comment]
> I would say that snapshots should be able to be timed in prod so that when time comes another content would be shown to users that are not logged in.
> 
> I have used them like this: edit content -> make publication -> edit content again and make new snapshot -> then edit times of the snapshots in question.

Hey @haivala 

Maybe the issue's description is not really clear, but the snapshot behavior shouldn't be changed here.


It's just for change the redirect after create the snapshot on admin, because for now it's redirecting to page update, but it should return to snapshot list.

**Comment by eerison** [comment]
> I would say that snapshots should be able to be timed in prod so that when time comes another content would be shown to users that are not logged in.
> 
> I have used them like this: edit content -> make publication -> edit content again and make new snapshot -> then edit times of the snapshots in question.

But if you want to elaborate an issue explaining better your proposal and open a PR, it should be good 😊

**Comment by mesiarm** [comment]
I agree, timing should be kept, but add another way to do same with fewer clicks. Button in edit page could have split dropdown, which opens small dialog with calendar and submit button. Or default action to publish now.

**Comment by haivala** [comment]
I really haven't thought how the timed snapshots could or should be achieved better (Like in the admin UI) but at the current state it is possible but needs little bit of hassle. I just wanted to open a discussion about the snapshots and let you know how timed snapshots can be used now. This is just a part of the UI where I imagined this functionality should be added.

I'm on a vacation now but after it l probably can open issue about this properly.

**Comment by jordisala1991** [comment]
On 4.x this is fixed.
