### ISSUE TITLE
[4.x] Remove code with NEXT_MAJOR comment 

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataPageBundle#1466]
To release the next major (4.x) we must Remove the code the contain the comment with `NEXT_MAJOR`

**Comment by eerison** [comment]
Is it fine to create this issue, to remember to remove the old code related with 4.x branch? Or do you think it isn't necessary?

Cc @VincentLanglet and @jordisala1991

**Comment by VincentLanglet** [comment]
It's a general rule we have when doing next major.
Also, we might remove all the next major, close the issue, and then deprecate a new things.

So im not sure about the interest of this issue

**Comment by eerison** [comment]
The idea is just make sure that all NEXT_MAJOR will be removed, but if it's a general rule, then it's fine, this issue is not necessary:)
