### ISSUE TITLE
Datagrid is still used

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataPageBundle#1477]
The datagrid bundle was removed on `4.x` branch, But still have code using things from there, is it sill necessary?

should be good test it and see if we can remove or provide other solution

just search for `Sonata\DatagridBundle` and you will find

for example: https://github.com/sonata-project/SonataPageBundle/blob/4.x/src/Entity/SiteManager.php#L16

**Comment by VincentLanglet** [comment]
You're linking to
```
use Sonata\Doctrine\Entity\BaseEntityManager;
```

Are you sure you looked at the 4.x branch ?

**Comment by eerison** [comment]
> You're linking to
> 
> ```
> use Sonata\Doctrine\Entity\BaseEntityManager;
> ```
> 
> Are you sure you looked at the 4.x branch ?

I guess I misunderstand something between branch `3.x` and `4.x`, sorry my bad
