### ISSUE TITLE
CMF Routing Configuration is poorly documented

### ISSUE THREAD

**Issue by mesiarm** [sonata-project/SonataPageBundle#1478]
https://docs.sonata-project.org/projects/SonataPageBundle/en/3.x/reference/installation/#cmf-routing-configuration

offers cmf_routing or router_auto_register, but doesn´t state, what is difference between them and when use which one.

**Comment by VincentLanglet** [comment]
@eerison @haivala Do you know something about this ?

PR with docs are always welcomed

**Comment by eerison** [comment]
well I do not have any idea about this :/

**Comment by haivala** [comment]
Never used the cmf_routing but I guess it has something to do with the old ability to edit blocks in front end and this would generate api routes for it

**Comment by jordisala1991** [comment]
Maybe we should point to the cmf router docs, but IMHO we shouldnt duplicate docs. Here we should just say what is the default config (recommended by us) and link to the bundle/component docs, so people can understand better about that code.
