### ISSUE TITLE
Breadcrumbs are not appearing into the pages

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataPageBundle#1497]
In 4.x branch the homepage looks strange.

it's the page for 3.x branch
<img width="1425" alt="Screenshot 2022-07-26 at 16 46 10" src="https://user-images.githubusercontent.com/6358755/181040596-d5a3c2ff-a82f-455f-aaf5-ab908d6b1bd9.png">

it's the same page for 4.x branch

<img width="1149" alt="Screenshot 2022-07-26 at 16 58 28" src="https://user-images.githubusercontent.com/6358755/181040661-4e9b31ce-0d73-4823-968e-be0cb92ae152.png">

**Comment by eerison** [comment]
I'm working on this ticket!

**Comment by eerison** [comment]
Hey @jordisala1991 do you know where this `breadcrumb` is rendered?

<img width="1662" alt="Screenshot 2022-08-04 at 09 18 32" src="https://user-images.githubusercontent.com/6358755/182787770-e0052478-259b-4651-8087-a00ff785451b.png">


I saw that it's handled when call this `{{ sonata_block_render_event('breadcrumb', { 'context': 'page', 'current_uri': app.request.requestUri }) }}`, but do you know exactly where?

~~I know it's in blockBundle!~~ (I'm not sure any more if it's handled in block bundle 😄 )

**Comment by haivala** [comment]
KNPMenuBundle?

**Comment by eerison** [comment]
> KNPMenuBundle?

Yeah I guess it's build by `KNPMenuBundle`, But I wan't to know where in the sonata code is checking those values to pass to menu build!

**Comment by eerison** [comment]
It was solved into #1564
