### ISSUE TITLE
Action "compose" could not be found in access mapping.

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataPageBundle#1498]
The compose page is not working

Steps:

- use the branch 3.x create the page and add some blocks
- switch to 4.x branch and try to access the compose page for example:`http://localhost:8001/admin/app/sonatapagepage/652/compose`

you should get an internal server error: 

```
Action "compose" could not be found in access mapping. Please make sure your action is defined into your admin class accessMapping property.
```

Stack trace

```
InvalidArgumentException:
Action "compose" could not be found in access mapping. Please make sure your action is defined into your admin class accessMapping property.

  at vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php:1692
  at Sonata\AdminBundle\Admin\AbstractAdmin->checkAccess('compose')
     (vendor/sonata-project/page-bundle/src/Controller/PageAdminController.php:158)
  at Sonata\PageBundle\Controller\PageAdminController->composeAction(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:29)     
```

**Comment by VincentLanglet** [comment]
This property
https://github.com/sonata-project/SonataPageBundle/blob/4.x/src/Admin/PageAdmin.php#L51
must be moved into this method
https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Admin/AbstractAdmin.php#L2166

Same should be done for others admins.

Can one of you make the PR @eerison @Hanmac ?

**Comment by Hanmac** [comment]
> This property https://github.com/sonata-project/SonataPageBundle/blob/4.x/src/Admin/PageAdmin.php#L51 must be moved into this method https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Admin/AbstractAdmin.php#L2166
> 
> Same should be done for others admins.
> 
> Can one of you make the PR @eerison @Hanmac ?

i assume as MR for 4.x ?

**Comment by eerison** [comment]
> > This property https://github.com/sonata-project/SonataPageBundle/blob/4.x/src/Admin/PageAdmin.php#L51 must be moved into this method https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Admin/AbstractAdmin.php#L2166
> > Same should be done for others admins.
> > Can one of you make the PR @eerison @Hanmac ?
> 
> i assume as MR for 4.x ?

yes, I guess all PR should be for 4.x now 👀
