### ISSUE TITLE
Introduce setting to hide Block List from Page Admin

### ISSUE THREAD

**Issue by haivala** [sonata-project/SonataPageBundle#1602]
This forces users to use composer and they are not confused by the Block list

**Comment by VincentLanglet** [comment]
The current stable branch is 3.x. I assume you're talking about 4.x but it's not even clear in you one-line-issue.
The more it's described, it's even better with screenshot and url, the more it will be solved.

**Comment by haivala** [comment]
As this is new feature request I thought it would be better to have new issue about it and not require it in 4.x release.

Basically to have setting `sonata_page.hide_block_list_admin` with boolean to hide Block list child admin from Page admin side menu .

This is would be nice to have not any way mandatory

**Comment by haivala** [comment]
![2022-09-08_122943-area](https://user-images.githubusercontent.com/3918267/189087786-de45422b-799c-4011-921d-c01e9934fe1b.png)
This is the side menu now, this setting would hide the Block list child admin

**Comment by jordisala1991** [comment]
IMO, you can implement a Admin extension attached to page, that manipulates the tab menu, and removes that link.

I think we should not add more options to page-bundle configuration.
