### ISSUE TITLE
Support the new Symfony 5.3 Runtime with multisite host_with_path

### ISSUE THREAD

**Issue by haivala** [sonata-project/SonataPageBundle#1604]
## Feature Request for 4.x

Runtime: https://symfony.com/doc/current/components/runtime.html
Multisite: https://docs.sonata-project.org/projects/SonataPageBundle/en/4.x/reference/multisite/

> The purpose of the Runtime component is to abstract most of the application bootstrapping logic into so-called runtimes, allowing you to write generic front-controllers. This will make Symfony applications easier to maintain, because the front-controller code can be moved to a [Symfony Flex recipe](https://symfony.com/doc/3.4/setup/flex.html) managed automatically by Symfony.

from https://symfony.com/blog/new-in-symfony-5-3-runtime-component

Current implementation needs changes to index.php to be able to use host_with_path multisite and I'm guessing we would need page runtime now

**Comment by eerison** [comment]
Yeah after release 4.0, it would be a good feature for multi sites ❤️

**Comment by haivala** [comment]
This should not be closed

**Comment by haivala** [comment]
Should we keep this one?
