### ISSUE TITLE
Add ability to append asset version which changes, when asset content changes 

### ISSUE THREAD

**Issue by mesiarm** [sonata-project/SonataPageBundle#1617]
Add option (maybe versioning: true) to sonata_page > assets in sonata_page.yaml

**Comment by haivala** [comment]
How does it work?

**Comment by jordisala1991** [comment]
We are using standard asset function. Afaik that function can already handle versioning.

**Comment by mesiarm** [comment]
> We are using standard asset function. Afaik that function can already handle versioning.

I could´t get working versioning in twig asset function, but found some solution using custom code and it worked for me : https://symfony.com/doc/current/frontend/custom_version_strategy.html
