### ISSUE TITLE
If Block does not implement EditableBlockService don't show it in composer

### ISSUE THREAD

**Issue by haivala** [sonata-project/SonataPageBundle#1621]
## Feature Request
If Block does not implement EditableBlockService don't show it in page composer as it only triggers errors.

**Comment by haivala** [comment]
In BlockAdmin the block that does not implement EditableBlockService should be shown but it should be indicated somehow that it cannot be used?

**Comment by eerison** [comment]
@haivala could you confirm if jordi's PR fixed your issue, if yes could you close?

**Comment by haivala** [comment]
@eerison yes it fixed it!

@jordisala1991 & @VincentLanglet You were taking about the implementation: I think that the "old way" would be still good: Make block maker define block setting that is the block `context` as an array but this time it would need proper documentation. if it has `sonata_page_block` then show it in the page composer and BlockAdmin. I'm only aware that there is another context `admin` that makes sure that the block is only used in SonataAdmin like in the dashboard.
