### ISSUE TITLE
Relate blocks with shared_blocks

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataPageBundle#1622]
I don't know if it should be a feature or a bug, But we have this case

When I create a shared block I didn't have any foreign key  to relate with others blocks for example.
<img width="1513" alt="Screenshot 2022-09-28 at 15 15 49" src="https://user-images.githubusercontent.com/6358755/192788934-540aa1fa-8ff8-4ee6-8866-dc249df96276.png">

then what I was thinking is create a oneToMany relationship with block

then all share_blocks will have the relation with blocks that are using that share_block, and if some one try to remove a share_block that is used in some page, then it will be return an error messaging saying that this block is used for others pages

**Comment by jordisala1991** [comment]
Better as a feature, it is not a bug.
