### ISSUE TITLE
Page duplication action to another site

### ISSUE THREAD

**Issue by mesiarm** [sonata-project/SonataPageBundle#1629]
## Feature Request

Add button and/or command to duplicate page with all fields and blocks to another site (then translate and use it in another locale). It would help to speed up development of multi locale webpages. There are other steps which could follow, like sync command, which will sync page in default site with all pages in another sites (with other locales). Also there could be posibility to select translatable fields which won´t be overwritten. Sync command reqires ability to link pages with same route but different site (locale) like mentioned here #1616

**Comment by eerison** [comment]
Have you tried to use shared blocks?

**Comment by eerison** [comment]
duplicate blocks sounds not like a good approach

**Comment by mesiarm** [comment]
> duplicate blocks sounds not like a good approach

shared blocks would help a little, but when I was creating page for another locale I would still need assign all shared blocks to this page again. And I ilso means page settings like template, position, alias which are same for both pages (same page but with different site and different locale)

**Comment by eerison** [comment]
"maybe" the same solution that was taken for shared blocks we could do for shared pages

like 1 page can be into many sites.

**Comment by mesiarm** [comment]
> "maybe" the same solution that was taken for shared blocks we could do for shared pages
> 
> like 1 page can be into many sites.

When I am creating copy of page in another locale I duplicate page and then translates text blocks into another language. So it is page with same blocks, same images in blocks, but translated text blocks.

**Comment by mesiarm** [comment]
I have found simmilar issue #441 and joining sites with same content in different locales would help to create Language switcher: #394

**Comment by haivala** [comment]
One piece of the puzzle: https://github.com/sonata-project/SonataPageBundle/issues/1367

We should actually collect all of the issues that mention i18n to one issue? Clearly there is lots to do.
