### ISSUE TITLE
[4.x] doctrine extension version is wrong?

### ISSUE THREAD

**Issue by haivala** [sonata-project/SonataPageBundle#1648]
https://github.com/sonata-project/SonataPageBundle/blob/4.x/composer.json#L30 should be 
`"sonata-project/doctrine-extensions": "^1.18 || ^2.0",`

https://github.com/sonata-project/sonata-doctrine-extensions/releases
version 2.1 does not exist

**Comment by eerison** [comment]
The version is correct 

Because we added this interface 
https://github.com/sonata-project/sonata-doctrine-extensions/blob/2.x/src/Model/TransactionalManagerInterface.php

@VincentLanglet or @jordisala1991 could you create a version 2.1.0?

**Comment by VincentLanglet** [comment]
Done
