### ISSUE TITLE
Remove Twig form_themes

### ISSUE THREAD

**Issue by Hanmac** [sonata-project/SonataPageBundle#1699]
## Feature Request

After https://github.com/sonata-project/form-extensions/pull/444 gets into a Release,
then this can be removed:
https://github.com/sonata-project/SonataPageBundle/blob/489e2fa48ce170b73e8bebc7ca9c10fac1d7778e/src/DependencyInjection/SonataPageExtension.php#L35-L45

This should be BC, and with a notice to remove the method and `implements PrependExtensionInterface` NEXT_MAJOR

**Comment by VincentLanglet** [comment]
https://github.com/sonata-project/form-extensions/pull/444 is released @Hanmac 
In 1.20.0 and soon in 2.0.0
