### ISSUE TITLE
Switch cocur/slugify to symfony/string

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataPageBundle#1713]
## Switch cocur/slugify to symfony/string

in order to use more symfony packages and keep this repo using the same dependencies as [admin bundle](https://github.com/sonata-project/SonataAdminBundle/blob/4.x/composer.json#L60C10-L60C24)

I suggest we change [slugify](https://github.com/sonata-project/SonataPageBundle/blob/4.x/composer.json#L25) to `symfony/string`!

in case it makes sense, then I will try to do it :D

**Comment by VincentLanglet** [comment]
> in case it makes sense, then I will try to do it :D

Sure it make sense ; but I dunno if we'll be able to drop the dependency in a BC way.

Pr is opened.

**Comment by eerison** [comment]
Yeah, we need to keep the dependency in 4.x and remove in 5.x only. 

We need the both dependencies to keep BC compatibility

**Comment by haivala** [comment]
@eerison Any chance you could finish this?

**Comment by eerison** [comment]
Hello @haivala 

unfortunately  I am without free time :/
