### ISSUE TITLE
Decorate `BlockAdmin`, `SnapshotAdmin` and `CreateSnapshotService`

### ISSUE THREAD

**Issue by sad270** [sonata-project/SonataPageBundle#1743]
## Subject
Hello 👋🏻 

I need to decorate `BlockAdmin` but I see in https://github.com/sonata-project/SonataPageBundle/blob/4.x/src/Controller/PageAdminController.php there is two `\assert($blockAdmin instanceof BlockAdmin);`

As BlockAdmin is `final`, we can not extend it. That mean this assert will only allow the `BlockAdmin`.

Instead of asserting it's BlockAdmin, I think we need to assert it's a `BaseBlockAdmin` (or `AbstractAdmin`)?

I see there is the same thing with `SnapshotAdmin` and `CreateSnapshotService` in `PageAdminController` and `SiteAdminController`. In my case, I don't need to decorate them, but it can help the community if we do the same for them 😄
For `SnapshotAdmin` we can assert it's a `AbstractAdmin`
For `CreateSnapshotService` we can assert it's a `CreateSnapshotBySiteInterface` or a `CreateSnapshotByPageInterface`

All this `\assert` have been introduce in #1570

**Comment by VincentLanglet** [comment]
Hi. The question would be WHY you need to decorate admins ?
You shouldn't need this, since there is already a feature named AdminExtension to add extra behavior to admins.

**Comment by sad270** [comment]
Hi @VincentLanglet ,
I'm migrating an old project, and we override lots of methods of `BlockAdmin`, but I checked except the method `generateBaseRoutePattern` it seems we can use AdminExtension for the rest instead of decoration.

Do you think that it is possible to modify AdminExtension to add extra behavour to `generateBaseRoutePattern` ?

like adding something like this in `AbstractAdmin::generateBaseRoutePattern`
```php
        foreach ($this->getExtensions() as $extension) {
            $baseRoutePattern = $extension->generateBaseRoutePattern($this, $baseRoutePattern);
        }
        
        return $baseRoutePattern;
```

And maybe do the same for `AbstractAdmin::generateBaseRouteName`

**Comment by sad270** [comment]
It is not recommended to decorate Sonata Admin's ? Now, all extra behavour must be done in AdminExtension ?

**Comment by VincentLanglet** [comment]
> It is not recommended to decorate Sonata Admin's ? Now, all extra behavour must be done in AdminExtension ?

I would say this was not intended like this at the first place. All admins in the docs are declared final and it seems like adminExtension was made for the decoration ; because it's more powerful. One adminExtension can work for several admins. But I wasn't there at the creation of this lib.

> Do you think that it is possible to modify AdminExtension to add extra behavour to `generateBaseRoutePattern` ?
> 
> like adding something like this in `AbstractAdmin::generateBaseRoutePattern`
> 
> ```
>         foreach ($this->getExtensions() as $extension) {
>             $baseRoutePattern = $extension->generateBaseRoutePattern($this, $baseRoutePattern);
>         }
>         
>         return $baseRoutePattern;
> ```
> 
> And maybe do the same for `AbstractAdmin::generateBaseRouteName`

I curious about what is needed to do in such methods, because the base route pattern and base route name are very specific to an admin and doesn't seems to need to be extended/decorated.

> All this `\assert` have been introduce in #1570

If you want, you can try to open a PR with change like
```
\assert($blockAdmin instanceof BlockAdmin);
```
into
```
\assert($blockAdmin instanceof AdminInterface);
```
(and same for SnapshotAdmin)

And same for CreateSnapshotService => interface.

If the build pass, it should be ok for us.

**Comment by sad270** [comment]
@VincentLanglet
> I curious about what is needed to do in such methods, because the base route pattern and base route name are very specific to an admin and doesn't seems to need to be extended/decorated.

If you want, you can target only one Admin with your AdminExtension, that's what you can do with `target` attribute of `sonata.admin.extension`.
> target: Admins service’s name that you want to customize, If you use the global attribute as true, you don’t need to pass it.
> https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/extensions/

So, when the extension target only one admin it make sense. It's an alternative of decoration.

IMO we need 2 PR:
* A `fix` where we remove `assert`. IMO they should be removed, but we will see in the PR
* A `feat` in SonatAdminBundle to add  `generateBaseRoutePattern` and `generateBaseRoutePattern` in AdminExtension

When I have time i will do the PR and we will see :D

**Comment by VincentLanglet** [comment]
Hi @sad270 will be fixed by https://github.com/sonata-project/SonataPageBundle/pull/1760
