### ISSUE TITLE
Add sonata_page twig extension

### ISSUE THREAD

**Issue by mesiarm** [sonata-project/SonataPageBundle#1748]
## Feature Request

Like recently added sonata_page_path please add sonata_page twig extension, which returns page object. Usable to get page name and other properties in twig.

**Comment by eerison** [comment]
Could you open `feature issues` that you want to implement, please.

**Comment by mesiarm** [comment]
> Could you open `feature issues` that you want to implement, please.

Do you mean pull request?

**Comment by eerison** [comment]
> > Could you open `feature issues` that you want to implement, please.
> 
> Do you mean pull request?

<img width="556" alt="Screenshot 2024-02-20 at 13 54 22" src="https://github.com/sonata-project/SonataPageBundle/assets/6358755/f35bc5ca-0613-46f5-a98d-e2f17b3471f6">

**Comment by VincentLanglet** [comment]
> Like recently added sonata_page_path please add sonata_page twig extension, which returns page object. Usable to get page name and other properties in twig.

sonata_page_path is returning the path when you pass the page object.

If you want the page object, you'll need the identifier (and doing a request to your db) or the admin (and accessing with getSubject). There is no need for a twig extension for this.
If the feature request is about something else, it requires more explanations
