### ISSUE TITLE
The function "knp_menu_render" does not exist in SonataAdminBundle:CRUD:base_list.html.twig

### ISSUE THREAD

**Issue by warmaschine** [sonata-project/SonataPageBundle#218]
I got this error when I launch my entity list (http://localhost/app_dev.php/admin/annsline/book/flight/list) with SonataAdminBundle

The function "knp_menu_render" does not exist in SonataAdminBundle:CRUD:base_list.html.twig at line 20 

this is similar to this issue: https://github.com/sonata-project/SonataAdminBundle/issues/277, but this problem is resolved.

**Comment by jordisala1991** [comment]
Probably solved already
