### ISSUE TITLE
Displaying menu on the frontend

### ISSUE THREAD

**Issue by craigwillis85** [sonata-project/SonataPageBundle#293]
I have created several pages, but I cannot seem to get these to display as a menu in my template/frontend

I have a page 'homepage' that is the parent of the other pages, but this doesn't create a menu.

Am I doing this right?

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
