### ISSUE TITLE
Unrecognized options "assets" under "sonata_admin"

### ISSUE THREAD

**Issue by Avtonom** [sonata-project/SonataPageBundle#324]
1. Unrecognized options "assets" under "sonata_admin"
2. Unrecognized options "add_block" under "sonata_admin.templates"

        "sonata-project/page-bundle": "2.3.6",
        "sonata-project/cache-bundle": "2.1.6",
        "sonata-project/block-bundle": "2.2.11",
        "sonata-project/cache": "~1",
        "sonata-project/admin-bundle": "2.2.11",
        "sonata-project/seo-bundle": "~1.1",
        "sonata-project/doctrine-extensions" : "1.*",
        "sonata-project/core-bundle": "2.2.5",
        "sonata-project/exporter": "1.3.3",
        "sonata-project/notification-bundle": "~2.2",
        "sonata-project/doctrine-orm-admin-bundle": "2.2.7",
        "sonata-project/easy-extends-bundle": "~2.1",
        "sonata-project/jquery-bundle": "<=1.9.1",

config.yml from http://sonata-project.org/bundles/admin/master/doc/reference/configuration.html

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
