### ISSUE TITLE
host_with_path_by_locale => redirection on root

### ISSUE THREAD

**Issue by Nikoms** [sonata-project/SonataPageBundle#328]
Hello,

I'm new with SonataPageBundle, and I have a little question.

I have 2 websites:
host: site1.com - path: /fr - locale: fr
host: site1.com - path: /en - locale: en

When I go on http://site1.com/app_dev.php/fr or 
http://site1.com/app_dev.php/en, everything works fine. 

But when I go on 
http://site1.com/app_dev.php, i'm redirected to 
http://site1.com/fr and of course, I have a 404 error becaure there isn't the "app_dev.php".

Did I forget something? 

Thank you for your help

**Comment by Nikoms** [comment]
That's it :-)
Le 9 janv. 2015 10:21, "Jasper De Craecker" <notifications@github.com> a
écrit :

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
