### ISSUE TITLE
Return Response from "internal" route without rendering the base template.

### ISSUE THREAD

**Issue by timmtim** [sonata-project/SonataPageBundle#336]
By default, the response from a controller action is wrapped in the template. I want to retrieve an HTML response through an AJAX request and dynamically update a part of the page. How can i achieve this with the SonataPage bundle enabled. 

My current solution is to return a JsonResponse with the raw HTML. My goal is to return a normal Response and disable the default rendering behaviour.

**Comment by ronanguilloux** [comment]
+1

**Comment by jordisala1991** [comment]
Closed as the solution is well documented
