### ISSUE TITLE
Clear symfony2's reverse-proxy cache on snapshot publication

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataPageBundle#346]
I'm using [symfony2's reverse-proxy cache](http://symfony.com/doc/current/book/http_cache.html#symfony2-reverse-proxy) to test esi without installing varnish. It looks like it isn't cleared when I change something in a page an make a publication.
An obvious workaround is to run the cache:clear command :

    app/console cache:clear

**Comment by core23** [comment]
Still present @greg0ire ?

**Comment by greg0ire** [comment]
Unable to test this, sorry!
