### ISSUE TITLE
API development status

### ISSUE THREAD

**Issue by Wharenn** [sonata-project/SonataPageBundle#354]
This is the todo list for the page bundle part of the Sonata API 

## Global

- [ ] Complete descriptions

## SITE

- [ ] Handle POST request
- [ ] Write Behat tests for GET/POST/PUT/DELETE requests

### Behat tests
- [ ] Optimize Behat tests by splitting full workflow test into separated and less interdependent Page, Block and Snapshot tests
- [ ] Test case covering data validation

**Comment by core23** [comment]
This issue is very old. Feel free to reopen if this issue is still present.
