### ISSUE TITLE
RFC: Is there interest for a page:clone command

### ISSUE THREAD

**Issue by koyaan** [sonata-project/SonataPageBundle#378]
I´m in the process of releasing successive language versions of a site and made a primitive page clone command to fill the new language sites for the translators.

á la `app/console sonata:page:clone --sourcesite=1 --destsite=2 --prefix="[en] "``

Is there anybody else seeing this as useful? If yes i might flesh it out and add some switches like only clone cms or hybrid pages.

**Comment by jaroslavas** [comment]
:+1: 
Exactly what I need. Any news?

**Comment by koyaan** [comment]
I can push all i have so far in the next few days

**Comment by OskarStark** [comment]
Applied in #650
