### ISSUE TITLE
Language switcher

### ISSUE THREAD

**Issue by wizart** [sonata-project/SonataPageBundle#394]
Hi,
how switch to another site (language switcher)? 
I have 3 languages (sites) and pages structure is same for all sites. 
How switch from one site (domain.com/en/about/) to another (domain.com/fr/about/).

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
