### ISSUE TITLE
host_with_path_by_locale - avoid annoying redirection

### ISSUE THREAD

**Issue by ragusa87** [sonata-project/SonataPageBundle#404]
If the url is not on a valid site, HostPathByLocaleSiteSelector is using a redirection to the default site.
Redirections should happend only on the front page, otherwise routes used by the default router are not available.

Example: 
I have 2 sites:
- French, with /fr as path and fr as locale
- English, with /en as path and en as locale

If I visit /admin , I am redirected to the default site instead of seeing sonata admin. This is due to a redirection to /login who redirects me to the default site. 
I should use /fr/login to access administration.

I don't know if it is a configuration problem. Anyway I found out that avoiding the redirection helps a lot with Sonata Admin.

I propose the following patch.
File: Site\HostPathByLocaleSiteSelector 
```php
        // no valid site, but try to find a default site for the current request
        if (!$this->site && count($enabledSites) > 0) {
            $defaultSite = $this->getPreferredSite($enabledSites, $request);
            // Redirecting user to the default site only from the front url.
            if("/" == $request->getPathInfo())
                $event->setResponse(new RedirectResponse($defaultSite->getUrl()));
        } elseif ($this->site && $this->site->getLocale()) {
            $request->attributes->set('_locale', $this->site->getLocale());
        }

```

Using : 

- Symfony v2.5.5 2aef97bbc95d0c4ae63537cca81bd6d984427d81
- SonataPage dev-master 4bbf8eb06198565ac2fd0ed050b21d5e954e26c1

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
