### ISSUE TITLE
Multisite - on create page redirect

### ISSUE THREAD

**Issue by pixel-paul** [sonata-project/SonataPageBundle#407]
When creating a new page, a site is selected, and details entered. On success,the user is then redirected to the page list, however the page list is the default site - not the site for which the page has been created. This is very confusing.

**Comment by OskarStark** [comment]
Which version are you using?

``composer show -i | grep sonata``

**Comment by pixel-paul** [comment]
I have encountered this problem in both 2.3 and 2.4

**Comment by OskarStark** [comment]
can you please post the output? maybe its a weird combination of packages

**Comment by pixel-paul** [comment]
sonata-project/admin-bundle                      dev-master de100fb 
sonata-project/block-bundle                      dev-master 01b65b4 
sonata-project/cache                             dev-master 0f2437f 
sonata-project/cache-bundle                      dev-master db96fc7 
sonata-project/classification-bundle             dev-master edd5f24 
sonata-project/comment-bundle                    dev-master d52d523 
sonata-project/core-bundle                       2.3.4              
sonata-project/datagrid-bundle                   dev-master fec0147 
sonata-project/doctrine-extensions               1.0.2              
sonata-project/doctrine-orm-admin-bundle         dev-master 2cd7097 
sonata-project/easy-extends-bundle               dev-master 55deba6 
sonata-project/ecommerce                         dev-develop 425a493
sonata-project/exporter                          dev-master 92835b5 
sonata-project/formatter-bundle                  dev-master 0a3a911 
sonata-project/google-authenticator              1.0.2              
sonata-project/intl-bundle                       dev-master d1ce9cf 
sonata-project/media-bundle                      dev-master adbefc8 
sonata-project/news-bundle                       dev-master 1a76607 
sonata-project/notification-bundle               dev-master a7023e2 
sonata-project/page-bundle                       dev-master e8bed93 
sonata-project/seo-bundle                        2.0.0              
sonata-project/sonata-composer                   dev-master 6ebe1f3 
sonata-project/timeline-bundle                   dev-master 19ef821 
sonata-project/user-bundle                       dev-master 0779677

**Comment by jordisala1991** [comment]
Issue is too old, and with outdated Sonata packages. For the info provided (not much) seems a problem related more with how sonata works, because without further configuration, list filters are not stored anywhere.

Closing for now, if you still having this issue, please ping me to reopen, and provide more information to solve your problem.
