### ISSUE TITLE
Missing css in tree view

### ISSUE THREAD

**Issue by loconox** [sonata-project/SonataPageBundle#422]
In the last commit on branch master. The page tree in the admin section of the page bundle, the css disappeared.

Possible solution :
I think the the file sonata-page.back.css is missing from the file tree.html.twig

**Comment by OskarStark** [comment]
@loconox what is the output of ``composer show -i | grep sonata`` ?

**Comment by loconox** [comment]
I'm sorry, I'm not using PageBundle anymore on my project.

**Comment by OskarStark** [comment]
@dunglas thank you for your help :+1: 

i will close this issue
