### ISSUE TITLE
Inconsistent behavior on function getBlocks()

### ISSUE THREAD

**Issue by loconox** [sonata-project/SonataPageBundle#425]
Here is my situation.
I created a custom Block that extends BaseBlockService. Based in that there are two cases where the call above returns different results :
$blockContext->getBlock()->getPage()->getBlocks()

Case 1 :
I make this call from the 'execute' function during the rendering of the block. It returns me only the direct children blocks of the Page. Not the children of the children recursively.
Case 2 :
I make this call from the 'buildEditForm' function (admin section). It returns me all children blocks, direct children and children of the children recursively.

Is this the expected behavior ?

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
