### ISSUE TITLE
getChildren() & ordered children pages

### ISSUE THREAD

**Issue by ronanguilloux** [sonata-project/SonataPageBundle#440]
`Page::getChildren()` return an unordered array of `Page` objects.
Since `PageInterface` has a `::getPosition()` method, IMHO, it would be nice to have an ordered, position-based, list of children, by default or as an option for `getChildren()`.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by jordisala1991** [comment]
https://github.com/sonata-project/SonataPageBundle/blob/3.x/src/DependencyInjection/SonataPageExtension.php#L173

This shows that the children are ordered. Closing
If you feel this issue is still relevant, please ping me to reopen, providing more information about the problem.
