### ISSUE TITLE
RFC: Multi-locale sites and page / block translation

### ISSUE THREAD

**Issue by jasperdcbe** [sonata-project/SonataPageBundle#441]
Hi, we are currently running into a problem where we have 2 websites on different URL's with exactly the same content. But the content has to be translated to 6 different languages.
This means we have to create multiple sites and pages + blocks for each sites/language. Not only will this be a lot of work, we will not have any relationship between page X on site A and page X on site B. Meaning we won't be able to have a "persistent" site switcher from site A to site B. For example. the user will always be redirected to the homepage.

A possible approach could be to:
- Allow assigning multiple locales and a default locale to a site
- Allow translation of pages and blocks to the locales linked to the site

This will have a huge impact on the configuration, Admin classes and SiteSelector strategies though. Also the "getPageByRouteName" method in the request listener would have to change. 

I'm looking forward to any feedback on this!

**Comment by bartoszmalec** [comment]
You have to implement some logic f.g. page mapper, and than connect pages. I know that it is't the best solution for normal pages.

I have problem with dynamic and hybrid pages. I would like to add controller with action to route urls:
- /en/hello/{name}
- /fr/bonjour/{name}

If I add 2 route annotations, sonata will generate two pages in both sites fr and en.

Do you know any solution to oblige Sonata to work with route translations f.g i18n-routing-bundle

**Comment by TheCelavi** [comment]
@bartosz-malec Yep, this is my problem as well, Sonata Page supports multi sites, but there is no any kind of support for i18n routing and dynamic/hybrid pages per site, that is, Sonata Page routing is not "site-aware", although this seams possible to implement....

**Comment by nicolasricci** [comment]
@bartosz-malec and @TheCelavi just bumped on this issue so I wanted to give my 2 cents since I had a similar issue.
I have tackled it by using a custom route loader (https://symfony.com/doc/2.8/routing/custom_route_loader.html) and created as many routing_xx.yml files as I had cultures in my application. 
Clearly not ideal but since I had only a few hybrid pages it worked well in my case. 
Hoping it could help someone else one day ;-)
