### ISSUE TITLE
Relation Type "Many To Many" for page - block entities

### ISSUE THREAD

**Issue by imilyukov** [sonata-project/SonataPageBundle#446]
Why not implemented relation "Many To Many" for pages, blocks entities??? Now, I must build one and the same block collection for each page(header, footer, etc.) again and again. It`s very unusefull. Current relation is "One To Many" must be "Many To Many".

**Comment by rande** [comment]
@imilyukov you have 2 options :
- you can use global page to share container blocks. see https://github.com/sonata-project/SonataPageBundle/blob/master/Resources/views/2columns_layout.html.twig#L17 for how to create and use a global page.
- the current master content a "Shared Block" feature to declare unlinked (from a page) block and you can use this block with the ``sonata.page.block.shared_block`` block.
