### ISSUE TITLE
Generating snapshots is very slow

### ISSUE THREAD

**Issue by blaues0cke** [sonata-project/SonataPageBundle#457]
We have a website with over 300 pages containg 1 to 20 blocks. The process generating snapshots takes over 120 seconds everytime. I think this should be improved to be faster. For me as a developer it is ok, but every customer will get annoyed when he has to do this everytime after he added a new block.

**Comment by rande** [comment]
@blaues0cke can you explain a bit more the use case ?

The ``SonataPageBundle`` is linked to the ``SonataNotificationBundle``, so by default the backend used by notification is ``runtime`` but you can select a database backend or a rabbitmq backend to offload the task to a background task. 

So the user will not have to wait to get the response from the server, but the snapshot generation will still take the same amount of time.

**Comment by blaues0cke** [comment]
Thank you. I just switched to `sonata.notification.backend.doctrine` and enabled a crontab to generate the snapshots. The snapshop-script also runs faster in the console so this fixes this problem at all. The user does not have to wait >120s and the server is faster processing the tasks.

**Comment by rande** [comment]
@blaues0cke you are welcome, please feel free to send use more information about your use case. It is a good way to improve this bundle. (and fix performance issue)
