### ISSUE TITLE
Incompatible interfaces with BlockAdminController::createAction

### ISSUE THREAD

**Issue by imilyukov** [sonata-project/SonataPageBundle#463]
After update I see this:

Fatal error: Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Runtime Notice: Declaration of Sonata\PageBundle\Controller\BlockAdminController::createAction() should be compatible with Sonata\AdminBundle\Controller\CRUDController::createAction(Symfony\Component\HttpFoundation\Request $request = NULL)' in /home/imilyukov/www/sanstyle.ru/vendor/sonata-project/page-bundle/Controller/BlockAdminController.php:122
Stack trace:
#0 /home/imilyukov/www/sanstyle.ru/vendor/jms/di-extra-bundle/JMS/DiExtraBundle/HttpKernel/ControllerInjectorsWarmer.php(60): Symfony\Component\Debug\ErrorHandler->handleError(2048, 'Declaration of ...', '/home/imilyukov...', 122, Array)
#1 /home/imilyukov/www/sanstyle.ru/vendor/jms/di-extra-bundle/JMS/DiExtraBundle/HttpKernel/ControllerInjectorsWarmer.php(60): JMS\DiExtraBundle\HttpKernel\ControllerInjectorsWarmer::findControllerClasses()
#2 /home/imilyukov/www/sanstyle.ru/vendor/jms/di-extra-bundle/JMS/DiExtraBundle/HttpKernel/ControllerInjectorsWarmer.php(35):  in /home/imilyukov/www/sanstyle.ru/vendor/sonata-project/page-bundle/Controller/BlockAdminController.php on line 122

**Comment by rande** [comment]
@imilyukov you also need to update the AdminBundle. We are fixing deprecated errors from symfony2.
