### ISSUE TITLE
Missing Assets on compose view

### ISSUE THREAD

**Issue by Spike81** [sonata-project/SonataPageBundle#466]
Hi, I've upgraded today to sonata page bundle 2.4 and I've noticed that in the compose page action when clicking on container the assets are missing, so js doesn't work and I can't add a block (url e.g. /admin/sonata/page/page/compose/container/2) but in the list of containers everything seems fine.

Yesterday I was using previous version (2.3) and everything seems fine, is there any solution to that except to downgrade?

Here's my composer.json
```
"sonata-project/core-bundle": "2.3.*@dev",
"sonata-project/admin-bundle": "2.4.*@dev",
"sonata-project/user-bundle": "2.3.*@dev",
"sonata-project/doctrine-mongodb-admin-bundle": "2.3.*@dev",
"sonata-project/easy-extends-bundle": "2.1.*@dev",
"sonata-project/block-bundle": "2.3.*@dev",
"sonata-project/doctrine-orm-admin-bundle": "2.3.*@dev",
"sonata-project/cache-bundle": "~2.2@dev",
"sonata-project/seo-bundle": "2.0.*@dev",
"sonata-project/notification-bundle": "~2.3@dev",
"symfony-cmf/routing-bundle": "~1.4@dev",
"sonata-project/page-bundle": "2.4.*@dev",
"sonata-project/datagrid-bundle": "2.2.*@dev"
```
In addition I've keep commented the assets config as official doc states in the sonata_admin config because if I enable them, the entire backend layout will result broken, here's the code what I'm talking about: 
```
#sonata page default assets (keep commentend just for consult)
    #assets: 
        #javascripts:
            #- bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
            #- bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.js
            #- bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            #- bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            #- bundles/sonatapage/sonata-page.back.min.js

        #stylesheets:
            #- bundles/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css
            #- bundles/sonataadmin/vendor/jqueryui/themes/flick/jquery-ui.min.css
            #- bundles/sonatapage/sonata-page.back.min.css
```
Moving this configuration from sonata_admin to sonata_page doesn't seems to provide benefits, as for decommenting last js and last css, the layout of compose container still remains broken

Any help will be appreciated, 

Thanks in advance

EDIT: in the tree view of containers, firebug js console throws following error:

ReferenceError: PageComposer is not defined
var composer = new PageComposer(ID_PAGE, {

**Comment by rande** [comment]
Please refer to https://github.com/sonata-project/sandbox/blob/2.4-develop/app/config/sonata/sonata_admin.yml for the complete listing of required assets. You need to uncomment non minified assets.

**Comment by Spike81** [comment]
Thanks for clarification, I'll try it

Good work
