### ISSUE TITLE
EasyExtends: ContextErrorException in SonataPageBundle.php line 57: Warning: call_user_func() expects parameter 1 to be a valid callback, class 'Application\Sonata\PageBundle\Entity\Page' not found

### ISSUE THREAD

**Issue by iantanwx** [sonata-project/SonataPageBundle#467]
Hello, I just started using the Sonata Bundles. I was able to install everything without any issues except for PageBundle - when I run the CLI command to generate the bundle, I get:

ContextErrorException in SonataPageBundle.php line 57:
Warning: call_user_func() expects parameter 1 to be a valid callback, class 'Application\Sonata\PageBundle\Entity\Page' not found

with stack trace:

in SonataPageBundle.php line 57
at ErrorHandler->handleError('2', 'call_user_func() expects parameter 1 to be a valid callback, class 'Application\Sonata\PageBundle\Entity\Page' not found', '/Users/iantanwx/Server/HuatFinance/vendor/sonata-project/page-bundle/SonataPageBundle.php', '57', array('container' => object(appDevDebugProjectContainer), 'class' => 'Application\Sonata\PageBundle\Entity\Page'))
at call_user_func(array('Application\Sonata\PageBundle\Entity\Page', 'setSlugifyMethod'), object(Closure)) in SonataPageBundle.php line 57
at SonataPageBundle->boot() in bootstrap.php.cache line 2347
at Kernel->boot() in bootstrap.php.cache line 2375
at Kernel->handle(object(Request)) in app_dev.php line 28

Checking into the configuration files under /DependencyInjection it seems that that is parameter the error is referring to. I am confused, since I thought that class was supposed to be generated with EasyExtends. It seems though that it will not work without it...

Any help much appreciated.

**Comment by adiuvonl** [comment]
Same issue here with the following composer.json (require part)

	"require" : {
		"php" : ">=5.3.3",
		"symfony/symfony" : "2.6.*",
		"doctrine/orm" : "~2.2,>=2.2.3,<2.5",
		"doctrine/dbal" : "<2.5",
		"doctrine/doctrine-bundle" : "~1.2",
		"twig/extensions" : "~1.0",
		"symfony/assetic-bundle" : "~2.3",
		"symfony/swiftmailer-bundle" : "~2.3",
		"symfony/monolog-bundle" : "~2.4",
		"sensio/distribution-bundle" : "~3.0,>=3.0.12",
		"sensio/framework-extra-bundle" : "~3.0,>=3.0.2",
		"incenteev/composer-parameter-handler" : "~2.0",
		
		"sonata-project/admin-bundle" : "dev-master",
		"sonata-project/propel-admin-bundle": "dev-master",
	    "sonata-project/cache-bundle": "dev-master",
	    "sonata-project/block-bundle": "dev-master",
	    "sonata-project/seo-bundle": "dev-master",
	    "sonata-project/easy-extends-bundle": "dev-master",
	    "sonata-project/notification-bundle": "dev-master",
	    "sonata-project/datagrid-bundle": "2.2.*@dev",
	    "sonata-project/doctrine-orm-admin-bundle": "dev-master",
	    "sonata-project/page-bundle": "dev-master",
	    
	    "symfony-cmf/routing-bundle": "~1.1"
	},

**Comment by haivala** [comment]
workaround:
install 2.3.8, do the easy-extend, install 2.3.9

**Comment by hdesousa** [comment]
Thanks. It worked for me.

**Comment by OskarStark** [comment]
this should be fixed in the current dev master

**Comment by bilougit** [comment]
@haivala :+1:

**Comment by haivala** [comment]
@OskarStark There is people who needs the stable version of this so the dev master is not an option

**Comment by jordisala1991** [comment]
Probably already fixed on 3.x and on a stable release

**Comment by jorenvh1** [comment]
I have the same issue. I added a porperty '$summary' on the page entity. When I try to render it I can an error

`An exception has been thrown during the rendering of a template ("Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Entity\Page\Page' does not have a method 'summary'").`

When I publish any page, this works again... Can anyone tell me how this is possible?
