### ISSUE TITLE
Missing composer style

### ISSUE THREAD

**Issue by blaues0cke** [sonata-project/SonataPageBundle#474]
Using the following setup will break the composer (this are the latest versions of the bundles):

        "sonata-project/markitup-bundle": "2.1.*@dev",
        "sonata-project/admin-bundle": "2.4.*@dev",
        "sonata-project/block-bundle": "2.3.*@dev",
        "sonata-project/cache-bundle": "2.2.*@dev",
        "sonata-project/classification-bundle": "2.3.*@dev",
        "sonata-project/datagrid-bundle": "2.2.*@dev",
        "sonata-project/doctrine-orm-admin-bundle": "2.4.*@dev",
        "sonata-project/easy-extends-bundle": "2.1.*@dev",
        "sonata-project/formatter-bundle": "2.4.*@dev",
        "sonata-project/intl-bundle": "2.2.*@dev",
        "sonata-project/notification-bundle": "2.3.*@dev",
        "sonata-project/media-bundle": "2.4.*@dev",
        "sonata-project/news-bundle": "2.4.*@dev",
        "sonata-project/page-bundle": "2.4.*@dev",
        "sonata-project/seo-bundle": "2.0.*@dev",
        "sonata-project/user-bundle": "2.3.*@dev",

It just looks like this:

![img_247_-_666x291 1](https://cloud.githubusercontent.com/assets/5159398/6846710/9aa9d02a-d3c0-11e4-90f8-a9e8ed950d37.png)

To make it work I have to extend `compose.html.twig` by:

    {% block javascripts %}
        {{ parent() }}
        <script src="{{ asset('bundles/sonatapage/sonata-page.back.min.js') }}" type="text/javascript"></script>
    {% endblock %}

    {% block stylesheets %}
        {{ parent() }}
        <link rel="stylesheet" href="{{ asset('bundles/sonatapage/sonata-page.front.min.css') }}" type="text/css" media="screen" />
    {% endblock %}

Since this is the replacement for a earlier version of this template:

    {% block javascripts %}
        {{ parent() }}
        <script src="{{ asset('bundles/sonatapage/composer.js') }}" type="text/javascript"></script>
    {% endblock %}

    {% block stylesheets %}
        {{ parent() }}
        <link rel="stylesheet" href="{{ asset('bundles/sonatapage/composer.css') }}" type="text/css" media="screen" />
    {% endblock %}

It works but is still not looking good:

![img_248_-_1192x615 1](https://cloud.githubusercontent.com/assets/5159398/6846745/f4dacdb0-d3c0-11e4-9c99-180f5e8aa66d.png)

Is this a bug or did I broke something while updating to the latest version?

**Comment by rande** [comment]
You can review the assets required: https://github.com/sonata-project/sandbox/blob/2.3-develop/app/config/sonata/sonata_admin.yml#L109-L190

The assetic package are defined here: https://github.com/sonata-project/sandbox/blob/2.3-develop/app/config/assetic.yml

**Comment by blaues0cke** [comment]
There is no relation to the sonatapage-composer stuff in the assets you listed

**Comment by rande** [comment]
Sorry wrong branch: https://github.com/sonata-project/sandbox/blob/2.4-develop/app/config/assetic.yml#L105

**Comment by blaues0cke** [comment]
Sorry, I dont think that this is the solution. We never hat do manage sonata-assets ourself before.

**Comment by rande** [comment]
@blaues0cke sorry about that, I guess it is a BC break. But this as been done to avoid loading to much assets from the backend as you can combine the js/css files from assetic.

**Comment by blaues0cke** [comment]
Ok but even when I load the files as you mentioned it does not work properly - only the solution i used in the issue it self worked since now

**Comment by mediamonks-robert** [comment]
I have this issue too but the comments do not make it clear on what should be done to actually fix this, any tips?

**Comment by mediamonks-robert** [comment]
My "fix" was to update the assets list in my config under "sonata_admin":

sonata_admin:
    assets:
        stylesheets:
            - bundles/sonataadmin/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/ionicons.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/AdminLTE.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonataadmin/vendor/select2/select2.css
            - bundles/sonataadmin/vendor/select2/select2-bootstrap.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonatapage/sonata-page.back.min.css

        javascripts:
            - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonataadmin/vendor/select2/select2.min.js
            - bundles/sonataadmin/App.js
            - bundles/sonataadmin/Admin.js
            - bundles/sonatapage/sonata-page.back.min.js

And now it's looking like it should, would like to hear if there is a better solution.
