### ISSUE TITLE
Too long block id will not fit into the database

### ISSUE THREAD

**Issue by blaues0cke** [sonata-project/SonataPageBundle#475]
When you use a too long block id (e.g. `longlongcompany.alsolongbundlename.supercoolandlongblocknamewithextranicefeatures` you will get an exception while rendering the frontend since the database is only able to store 64 characters. So after you added the block into a sonata page you will get an excetption telling you that the block `longlongcompany.alsolongbundlename.supercoolandlongblocknamewith` could not be found.

Think it would be nice when the system throws an exception when the id is too long.

**Comment by core23** [comment]
Not sure if this is a `bug`. We can improve the limit to 100 chars, but then someone else needs 101 chars... Can we find another solution or can you provide a PR? @blaues0cke

**Comment by blaues0cke** [comment]
A possible solution would be a error message since you can save a too long block id but then it causes a "wrong error" and you waste a lot of time debugging the wrong problem. Will try to think about a programmatically solution the next days.

**Comment by core23** [comment]
Feel free to fix it with a PR @blaues0cke
