### ISSUE TITLE
Sonata Page Bundle 2.3 problem with page visibility

### ISSUE THREAD

**Issue by Spike81** [sonata-project/SonataPageBundle#485]
Hi, I'm using Sonata Page Bundle 2.3 with a custom template, and after created with success a page and published the snapshot I got some trouble to see it in frontend.

The fact that happens is that the page it's visibile in frontend only by super admin user logged in, not for anonymous users or simple users without access to backend.

Is there some config option that I'm missing or maybe somw firewall configuration?

Any help would be appreciated

Thanks in advance,

Simone

**Comment by core23** [comment]
We don't support this branch anymore. Please check this issue against the latest stable / master version.

Feel free to create a new issue following the issue template, if this error ist still present.
