### ISSUE TITLE
possible to create a release to get #472 ??

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataPageBundle#486]
I need this commit

@rande is it possible to create a new release to get #472 ??

thank you!

**Comment by rande** [comment]
The work is not complete. We need to add check in the javascript to avoid an user to move a block inside a container where it is not possible.  Also we need to release the AdminBundle 2.4 before tagging this release. Of course you can help ;)

// cc @plouc

**Comment by OskarStark** [comment]
Thank you for the info!
Javascript... meeehh :)

**Comment by mediamonks-robert** [comment]
Any update on this? Seems like it's a great addition!

**Comment by OskarStark** [comment]
maybe @qsomazzi or @core23 can help us with the JS task?

**Comment by core23** [comment]
@OskarStark Which JS task do you mean?

**Comment by OskarStark** [comment]
> The work is not complete. We need to add check in the javascript to avoid an user to move a block inside a container where it is not possible. Also we need to release the AdminBundle 2.4 before tagging this release. Of course you can help ;)

this one :)

**Comment by core23** [comment]
Someone must have fixed this. Tested it yesterday and works as aspected: you can't move inapplicable blocks.

**Comment by plouc** [comment]
@rande, the work is done on the js side

**Comment by OskarStark** [comment]
really @plouc ?

**Comment by plouc** [comment]
yes. @rande ?

**Comment by core23** [comment]
There are some releases since opening this.
