### ISSUE TITLE
no help text shown??

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataPageBundle#488]
Hey!

When i have this:
![bildschirmfoto 2015-04-21 um 13 45 46](https://cloud.githubusercontent.com/assets/995707/7251652/a5492018-e82d-11e4-84fb-879a5989a646.png)

no help text is shown in the Block:
![bildschirmfoto 2015-04-21 um 13 45 55](https://cloud.githubusercontent.com/assets/995707/7251660/acf02dc0-e82d-11e4-8fdf-18d70b126395.png)

Is this expected?

if not i will have a look an will create a PR, but please give me a hint where i have to look....

Best
Oskar

**Comment by OskarStark** [comment]
PageBundle is correct? Or BlockBundle?

**Comment by OskarStark** [comment]
any idea? @rande

**Comment by rande** [comment]
@OskarStark no idea, I guess the related form template is missing the help rendering

**Comment by gremo** [comment]
You have to use `sonata_help` instead of `help` for sub fields (documented [here](https://sonata-project.org/bundles/admin/master/doc/reference/form_help_message.html)):

```php
$formMapper
    ->add('enabled')
    ->add('settings', 'sonata_type_immutable_array', array(
        'keys' => array(
            array('content', 'textarea', array(
                'sonata_help' => 'Set the content'
            )),
            array('public', 'checkbox', array()),
    ))
;
```

**Comment by greg0ire** [comment]
Thanks @gremo
