### ISSUE TITLE
where to edit error pages?

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataPageBundle#498]
Hey Guys, i found this:

https://sonata-project.org/bundles/page/master/doc/reference/error_pages.html

but where can i add text and html styling to (for example):

```
_page_internal_error_not_found
```

Thx!

**Comment by OskarStark** [comment]
@rande any idea?

**Comment by rande** [comment]
@OskarStark did you find your response ?

**Comment by OskarStark** [comment]
not really :)

2015-07-23 9:56 GMT+02:00 Thomas <notifications@github.com>:

**Comment by fatmah** [comment]
Hi,
you can add content to the  _page_internal_error_not_found page from the admin dashboard
