### ISSUE TITLE
Cannot add a new page, does not generate the url

### ISSUE THREAD

**Issue by janoist1** [sonata-project/SonataPageBundle#50]
If I try to create a new page the following error occures: The URL '/n-a' is already associated with another page
How to fix the url generation?

**Comment by houssem86** [comment]
I have the same probleme, I want to create a new page but it doesn't generate URL (It didn't create new URL in table phpcr_nodes). Also, I want that the new page will be composed from blocks which I can edit them without associating a template

**Comment by finchen** [comment]
same issue. on the demo site the page is created but has no url.
on my latest update, the page is not create:
`/ url already exists`

i have temporary fixed it by overriding PageAdmin
```
public function getNewInstance()
    {
        $instance = parent::getNewInstance();
        if ($instance->getParent() === null) {
            try {
                $parent = $this->pageManager->getPageByUrl($instance->getSite(), '/');
            } catch (PageNotFoundException $e) {
                throw new InternalErrorException('Unable to find the root url, please create a route with url = /');
            }
            $instance->setParent($parent ?: null);
        }

        return $instance;
    }
```

**Comment by houssem86** [comment]
Hi finchen,
I tried your solution but I had this error message : 
"Catchable Fatal Error: Argument 1 passed to Sonata\PageBundle\Entity\PageManager::getPageByUrl() must implement interface Sonata\PageBundle\Model\SiteInterface, null given"

**Comment by houssem86** [comment]
I fixed the error but this overriding like this : 
"    
public function getNewInstance() {
        $instance = parent::getNewInstance();

        if ($site = $this->getSite()) {
            $instance->setSite($site);
        }

        if ($instance->getParent() === null) {
            try {
                $parent = $this->pageManager->getPageByUrl($instance->getSite(), '/');
            } catch (PageNotFoundException $e) {
                throw new InternalErrorException('Unable to find the root url, please create a route with url = /');
            }
            $instance->setParent($parent ?: null);
        }

        return $instance;
    } 
"
But this did not fix my problem and the URL is not generated when I create a new page !

**Comment by houssem86** [comment]
I fixed the message error by overriding PageAdmin like this : 
    public function getNewInstance()
    {
        $instance = parent::getNewInstance();

        if ($site = $this->getSite()) {
            $instance->setSite($site);
        }

        if ($instance->getParent() === null) {
            try {
                $parent = $this->pageManager->getPageByUrl($instance->getSite(), '/');
            } catch (PageNotFoundException $e) {
                throw new InternalErrorException('Unable to find the root url, please create a route with url = /');
            }
            $instance->setParent($parent ?: null);
        }

        return $instance;
    }

But this did not fix my problem
