### ISSUE TITLE
Custom URL (not fully implemented ?)

### ISSUE THREAD

**Issue by Th3Mouk** [sonata-project/SonataPageBundle#502]
Hello everyone,

I've tried to analyse the workflow of the router, because the use of field 'custom URL' is obscure. 
In my project, except the corresponding field in the database, he's never considered.

I understand how the `CmsPageRouter.php` generate and match route of different page type, but the implementation the customURL seem forgotten for a part.

When a snapshot is created the `Transformer.php` do :

``` php
$snapshot->setUrl($page->getUrl());
$snapshot->setRouteName($page->getRouteName());
$snapshot->setPageAlias($page->getPageAlias());
$content['slug'] = $page->getSlug();
```

But when a snap is load :

``` php
$page->setCustomUrl($snapshot->getUrl());
$page->setUrl($snapshot->getUrl());
$page->setRouteName($snapshot->getRouteName());
$page->setPageAlias($snapshot->getPageAlias());
$page->setSlug($content['slug']);
```

So i conclude, that the snap doesn't care about it.

And in the `CmsPageRouter.php` I've found this :

``` php
/**
 * Returns the Url from a Page object
 *
 * @param PageInterface $page
 *
 * @return string
 */
protected function getUrlFromPage(PageInterface $page)
{
    return $page->getCustomUrl() ?: $page->getUrl();
}

/**
     * Generates an URL from a Page object
     *
     * @param PageInterface $page          Page object
     * @param array         $parameters    An array of parameters
     * @param bool|string   $referenceType The type of reference to be generated (one of the constants)
     *
     * @return string
     *
     * @throws \RuntimeException
     */
    protected function generateFromPage(PageInterface $page, array $parameters = array(), $referenceType = self::ABSOLUTE_PATH)
    {
        // hybrid pages use, by definition, the default routing mechanism
        if ($page->isHybrid()) {
            return $this->router->generate($page->getRouteName(), $parameters, $referenceType);
        }

        $url = $this->getUrlFromPage($page);

        if ($url === false) {
            throw new \RuntimeException(sprintf('Page "%d" has no url or customUrl.', $page->getId()));
        }

        return $this->decorateUrl($url, $parameters, $referenceType);
    }
```

IMO I miss part of the reasoning or a part of the workflow is missing.

Thanks for your help

**Comment by adamquaile** [comment]
I've just been doing the same investigation to try and figure out how the slug / custom url works and arrived at the same conclusion. 

It seems the custom url doesn't affect the snapshot in any way - there isn't even a DB column for that.

**Comment by rande** [comment]
Seems, you are right! There is a missing call in https://github.com/sonata-project/SonataPageBundle/blob/master/Entity/Transformer.php#L55-L112 ...

**Comment by rande** [comment]
Can you create a PR ?

**Comment by adamquaile** [comment]
@rande Would I be right in thinking it also needs mapping info in the entity and in BaseSnapshot.orm.xml ?

**Comment by Th3Mouk** [comment]
I can make a simple PR but how to manage with URL conflict ? If user enter a bad URL ?

**Comment by jordisala1991** [comment]
Does #1607 fix this issue?
