### ISSUE TITLE
enabled to shouldn't be mandatory

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataPageBundle#508]
![admin_create](https://cloud.githubusercontent.com/assets/995707/8845396/126f19e2-311f-11e5-8c81-1f77c42c7a18.jpg)

If i am right, i'll provide a PR

**Comment by rande** [comment]
Ok for me, but you need to check the different site selector to make sure the query is working

**Comment by jordisala1991** [comment]
You already implemented this on: https://github.com/sonata-project/SonataPageBundle/pull/549

Closing
