### ISSUE TITLE
Failing test with slugify

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataPageBundle#512]
https://travis-ci.org/sonata-project/SonataPageBundle/jobs/70202885#L382

@rande Any idea? This was not failing before. Failing on job restart.

**Comment by rande** [comment]
probably an issue with iconv on the running instance.

**Comment by Soullivaneuh** [comment]
@rande what do you mean?

**Comment by Soullivaneuh** [comment]
BTW, iconv support was removed from the used library a long time ago: https://github.com/cocur/slugify/blob/64360a07d565c0a212fc3735e1834123b4b99416/README.md#version-04-17-january-2014

**Comment by meyerbaptiste** [comment]
This is the code for BC that is executed during tests and not `cocur/slugify` because `Page::setSlugifyMethod()` is not called. So `iconv()` is used.

See:
* https://github.com/sonata-project/SonataPageBundle/blob/master/Tests/Model/PageTest.php#L23-L28
* https://github.com/sonata-project/SonataPageBundle/blob/master/Model/Page.php#L694

**Comment by Soullivaneuh** [comment]
@meyerbaptiste from where `$slugifyMethod` come from?

**Comment by meyerbaptiste** [comment]
From here : https://github.com/sonata-project/SonataPageBundle/blob/master/Model/Page.php#L81-L97
And it is setted during bundle boots : https://github.com/sonata-project/SonataPageBundle/blob/d9ff145f6d05ee9cc17c4f2b906a102b2e339bc9/SonataPageBundle.php#L52-L62

**Comment by Soullivaneuh** [comment]
Ok I see, thanks.

So it could be iconv false. But it's not explain why it was working before. Some recommendation about how to solve it?

**Comment by Soullivaneuh** [comment]
Fixed in https://github.com/sonata-project/SonataPageBundle/commit/317333b7f19046ae186a0a9837851752e3a84f5c.

Thanks @rande.
