### ISSUE TITLE
How to use `host_with_path` in PhpUnit?

### ISSUE THREAD

**Issue by jaroslavas** [sonata-project/SonataPageBundle#515]
I'm using `host_with_path` and when running PhpUnit tests, they fail with error:

```
You must change the main Request object in the front controller (app.php) in order to use the `host_with_path` strategy
```

Of course, app.php and app_dev.php are changed according to documentation and work well.

Is there a way to fix that?

PS. There was a question on [StackOverflow with the same problem](http://stackoverflow.com/questions/29433358/symfony2-phpunit-functional-testing-error-host-with-path).

**Comment by core23** [comment]
Can you provide more information? Please use the new issue template @jaroslavas

**Comment by sswebdis** [comment]
This strategy requires a dedicated RequestFactory object. So you need to alter the front controller to use the one provided by the PageBundle. To do so, open files: app.php and app_dev.php and change the following parts.
Note If you use app_test.php and/or app_*.php don’t forget to modify these files, too!
https://sonata-project.org/bundles/page/master/doc/reference/multisite.html

**Comment by jordisala1991** [comment]
Issue is old, with a provided solution. Closing, if thisis still relevant, ping me to reopen
