### ISSUE TITLE
dev-master -> JMS serializer Problem

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataPageBundle#522]
![bildschirmfoto 2015-09-02 um 18 01 35](https://cloud.githubusercontent.com/assets/995707/9636629/be52f9ca-519c-11e5-89b0-dc3bd5c50992.png)

@Soullivaneuh can we use the 1.0 here?
or is there a problem?

![bildschirmfoto 2015-09-02 um 18 02 55](https://cloud.githubusercontent.com/assets/995707/9636651/de7f4168-519c-11e5-930a-590f6e220589.png)

cc @rande

**Comment by Soullivaneuh** [comment]
We already set up 1.0 on another sonata bundle without issue.

You can try a PR for that with taking a look on upgrading note for jms and test sensible part of this bundle.

Please do it on 2.3 branch, latest stable.

**Comment by OskarStark** [comment]
@Soullivaneuh let's have a look at travis ;-)
