### ISSUE TITLE
Hybrid Homepage

### ISSUE THREAD

**Issue by stephenheron** [sonata-project/SonataPageBundle#537]
Hi,

I am having issues creating a Hybrid homepage. I have created a route/action that looks like this: 

```
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction(Request $request)
    {
        return $this->render('home.html.twig');
    }
```

and I am running:

```
 php app/console sonata:page:update-core-route --site=all
```

However I end up with two Homepage pages. One of them is a CMS page and the other is my Hybrid page. 

Looking at the code I think the issue can be traced back to here: https://github.com/sonata-project/SonataPageBundle/blob/master/Route/RoutePageGenerator.php#L89

The RoutePageGenerator will create a root CMS homepage page that is the very similar to my Hybrid page. This means that I need to go into the DB and update ID's and then delete the CMS homepage page. 

Could we perhaps offer the user an option to enter a default existing route as the root page?

I am happy to have a look at fixing the issue but I want to make sure I am not barking up the wrong tree first.

Thanks,
Stephen

**Comment by juanolon** [comment]
same here :)  @stephenheron i guess, you already have found this: http://stackoverflow.com/questions/32046565/customer-home-page-sonata-page but just in case..

**Comment by juanolon** [comment]
also, made a pull request #545 based on that response. it works on my workspace. so feel free to check it out ;)
