### ISSUE TITLE
css need to be fixed

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataPageBundle#554]
![bildschirmfoto 2015-10-30 um 10 29 45](https://cloud.githubusercontent.com/assets/995707/10842342/3e9eab5c-7ef1-11e5-8b43-52ab32e3f309.png)
![bildschirmfoto 2015-10-30 um 10 29 50](https://cloud.githubusercontent.com/assets/995707/10842343/3eb6c9d0-7ef1-11e5-95cd-3d76b264f429.png)

The height is wrong

**Comment by OskarStark** [comment]
Could someone provide a PR?

**Comment by OskarStark** [comment]
ping @core23

**Comment by core23** [comment]
Sorry, no idea how to solve it easy :/

**Comment by OskarStark** [comment]
Thanks for your feedback

**Comment by haivala** [comment]
I ran into same kind of situation. I solved it by making the content areas in 2 columns.. which is bad

This should be done in javascript so that the whole container height would adjust with the content. this would allow even bigger matrix

**Comment by haivala** [comment]
nice to have in this would be picture of the page overlay-ed on top of the container

**Comment by core23** [comment]
@ju1ius Can you help?

**Comment by OskarStark** [comment]
Maybe @mvhirsch can support us here :smiley:

**Comment by mvhirsch** [comment]
This could be done with CSS. But depends on supported browsers, see here: http://stackoverflow.com/a/12242226/6849366
