### ISSUE TITLE
Attempted to call method "setSecurityContext" on class "Sonata\PageBundle\Admin\BlockAdmin"

### ISSUE THREAD

**Issue by 0xMatt** [sonata-project/SonataPageBundle#563]
getting this error using page-bundle 2.3.x-dev & 2.4.x-dev with the appropriate admin dependency, unsure of what I might be missing to cause this issue. NotificationBundle dependency is installed and working correctly as well, here's composer.json's sonata deps:

        "sonata-project/admin-bundle": "2.3.x-dev",
        "sonata-project/page-bundle": "2.3.x-dev",
        "sonata-project/doctrine-orm-admin-bundle": "2.3.x-dev",

if anymore information is required I am more than happy to provide.

**Comment by core23** [comment]
We don't support this branch anymore. Please check this issue against the latest stable / master version.

Feel free to create a new issue following the issue template, if this error ist still present.
