### ISSUE TITLE
Impossible to access an attribute ("children") on a integer variable ("5") in SonataPageBundle:Block:block_core_children_pages.html.twig at line 20

### ISSUE THREAD

**Issue by netfarma** [sonata-project/SonataPageBundle#586]
Hello,

First thanks for Sonata project. I'm thiking to use it as a base code for my new projects. 

Unfortunally i got error after I add a block with type "Page", 
frontend says:

Impossible to access an attribute ("children") on a integer variable ("5") in SonataPageBundle:Block:block_core_children_pages.html.twig at line 20

See 68 line in https://github.com/sonata-project/SonataPageBundle/blob/master/Block/ChildrenPagesBlockService.php#L68
file

When I replace
$page = $settings['pageId'];
with
$page = $cmsManager->getPageById($settings['pageId']);
everything seems to be ok.

**Comment by core23** [comment]
This issue should be fixed in the latest stable / master version. Please have a look at the docs too.

If this is still present, feel free to reopen this issue
