### ISSUE TITLE
Best practices: Creating a global page on production

### ISSUE THREAD

**Issue by Neodork** [sonata-project/SonataPageBundle#591]
Hello there,

I've been going through the Sonata project. Trying to create my own setup. So far so good and I am very impressed by Sonata. However here is where I am stuck:

If I look into the Sonata sandbox, the global page (the page that handles the header, footer and default content) is created using a data fixture. This is however not preferred on a production server. What would be the best practice for creating a global page on a production setup?

Now if someone could leave me some steps or a guide to follow that be great. I can of course provide a PR with the code and maybe a cookbook article on how to do this, once I have it mapped out.

**Comment by OskarStark** [comment]
What about using the Code from the fixtures in a Migration and execute them
in the prod Server?

Am Freitag, 18. Dezember 2015 schrieb Lou :

**Comment by Neodork** [comment]
Thanks for clearing my doubt. I've recreated a migration file from the data fixture. The migration code uses some constant values to allow it to be easily reused. Other than that it is basically a copy + paste from the migration.

https://gist.github.com/Neodork/bbfb1b5d305f22a5a835

Feel free to give any feedback on the gist. This can be closed in my opinion.
