### ISSUE TITLE
page_defaults parameter not working

### ISSUE THREAD

**Issue by pulse00** [sonata-project/SonataPageBundle#60]
i'm trying to disable decoration for some pages whose routes are defined in my bundle. however, when i run the `update-core-routes` and `create-snapshot` commands, the `decorate` field is set to 1 in the database for the pages/snapshots.

I've searched through the code where the `page_defaults` configuration parameter is used to turn of decoration for those pages, but i cant't find this anywhere.

am i missing something here?

**Comment by jorenvh1** [comment]
Can anyone tell me how to disable decoration if not from the config? And also what this exactly does?
