### ISSUE TITLE
tree.html.twig trying to access currentSite throws error when no sites are configured.

### ISSUE THREAD

**Issue by StrikeForceZero** [sonata-project/SonataPageBundle#601]
When using the sonata admin bundle to edit pages without a site configured you get an error:

```
Impossible to access an attribute ("name") on a null variable in SonataPageBundle:PageAdmin:tree.html.twig at line 52
```

lines 51-53 from tree.html.twig
```twig
<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    <strong class="text-info">{{ currentSite.name }}</strong> <span class="caret"></span>
</button>
```

however few lines down; line 58 is checking to make sure currentSite is not null.
```twig
{% if currentSite and site.id == currentSite.id %}
```

suggesting to check if current site is null on line 52 like the sample snippet below.
``` twig
<strong class="text-info">{{ currentSite ? currentSite.name : 'No sites configured' }}</strong> <span class="caret"></span>
```

I can make a pull request if this is appropriate.

**Comment by OskarStark** [comment]
yes please create a PR and we will review it :+1: 

thank you @StrikeForceZero
