### ISSUE TITLE
sonata set target route in page with sonata-page-bundle

### ISSUE THREAD

**Issue by zayen** [sonata-project/SonataPageBundle#605]
Internal page redirection
This page is configured to redirect the end user to another page. In order to configure it, the redirect has been blocked for editor only. 

Please click here to follow the redirection: /.

??????

**Comment by rande** [comment]
The handler has detected an redirect response; this page will let you configure the redirect (ie, disable it). This behavior only happen if you are an editor.

**Comment by zayen** [comment]
how to disable this redirect.please give me steps

**Comment by zayen** [comment]
same problem, help me please

**Comment by thms** [comment]
Remove PAGE_EDITOR role from your user, by changing the hierarchy
