### ISSUE TITLE
Internal Error : No site available for the current request

### ISSUE THREAD

**Issue by aimeric** [sonata-project/SonataPageBundle#611]
Hi,

After the installation of sonataPageBunble i have an error when i'm trying to reach the pages of my website.

> Sonata Project - Internal Error No site available for the current request with uri http://127.0.0.1>/symfony/web/app_dev.php/index

i did run the following command:

`php app/console sonata:page:create-site
php app/console sonata:page:update-core-routes --site=all
php app/console sonata:page:create-snapshots --site=all`

`> php.exe C:\xampp\htdocs\Symfony\app\console sonata:page:create-site
Please define a value for Site.name : unify
Please define a value for Site.host : unify
Please define a value for Site.relativePath : /
Please define a value for Site.enabled : true
Please define a value for Site.enabledFrom : now
Please define a value for Site.enabledTo : +10 yeras 
Please define a value for Site.default : true
Please define a value for Site.locale : -`

config.yml

`````` sonata_page:
    multisite: host
    use_streamed_response: true # set the value  to false in debug mode or if the reverse proxy does not handle streamed  response
    ignore_route_patterns:
        -  ^(.*)admin(.*)   # ignore admin route, ie  route containing 'admin'
        -  ^_(.*)          # ignore symfony routes
    ignore_routes:
        -  sonata_page_cache_esi
        -  sonata_page_cache_ssi
        -  sonata_page_js_sync_cache
        -  sonata_page_js_async_cache
        -  sonata_cache_esi
        -  sonata_cache_ssi
        -  sonata_cache_js_async
        -  sonata_cache_js_sync
        -  sonata_cache_apc
    ignore_uri_patterns:
        - ^/admin\/   # ignore admin route, ie route containing  'admin'
    page_defaults:
        homepage: { decorate: false, enabled: true } # disable  decoration for homepage, key - is a page route
    default_template: default
    templates:
        default:  { path:  'ApplicationSonataPageBundle::demo_layout.html.twig',           name: 'default' }
        2columns: { path:  'ApplicationSonataPageBundle::demo_2columns_layout.html.twig', name: '2 columns layout' }
    catch_exceptions:
        not_found: [404]
        fatal:     [500]```
``````

**Comment by sumantiwari** [comment]
i am facing the same problem. do anyone have the solution for this?

**Comment by ptatar89** [comment]
what did you provide as host in Site definition in Admin? I had the same issue and I provided wrong host. Please check profiler exceptions there should be SQL which can help you resolve your issue

**Comment by sumantiwari** [comment]
i used localhost:8000 . can you help me ?
