### ISSUE TITLE
Page url not generated

### ISSUE THREAD

**Issue by rYsvelain** [sonata-project/SonataPageBundle#612]
Hello,

I'm using SonataPageBundle with most of the Sandbox bundles, but I have a problem when I create a page, the url is not defined. So I can't see my page in the front.

I tested this feature on the online demo and this is working well. I also installed the sandbox and this is not working locally on my sandbox.

So I can't find where is the problem, someone have an idea ?

These are my installed package : 
```
sonata-project/admin-bundle              2.3.7
sonata-project/block-bundle              2.2.13
sonata-project/cache                     1.0.7
sonata-project/cache-bundle              2.2.5           
sonata-project/classification-bundle     2.2.2            
sonata-project/core-bundle               2.3.10          
sonata-project/datagrid-bundle           dev-master 0749e71 
sonata-project/doctrine-extensions       1.0.2              
sonata-project/doctrine-orm-admin-bundle 2.3.3              
sonata-project/easy-extends-bundle       2.1.10             
sonata-project/exporter                  1.4.1              
sonata-project/formatter-bundle          2.3.3              
sonata-project/google-authenticator      1.0.2              
sonata-project/intl-bundle               2.2.3           
sonata-project/media-bundle              2.3.3            
sonata-project/news-bundle               2.3.5           
sonata-project/notification-bundle       2.3.2              
sonata-project/page-bundle               2.3.9           
sonata-project/seo-bundle                1.1.10         
sonata-project/translation-bundle        1.0.0          
sonata-project/user-bundle               2.2.4
```

**Comment by OskarStark** [comment]
did you run the following commands?

```
app/console sonata:page:update-core-routes --site=all
app/console sonata:page:create-snapshots --site=all
```

**Comment by rYsvelain** [comment]
Yes, I forgot to told you but when I run the snapshot creation command my urls are generated with the slug. But if you look the Demo sandbox, this is generated when the page is created.

How do you do that ? I can't run these two commands when my final users will manage the website ?

Thank you for your concern

**Comment by OskarStark** [comment]
```php

# app/config/config.yml

sonata_page:
    # ...
    # Generates a snapshot when a page is saved (from the admin)
    direct_publication: false # or %kernel.debug% if you want to publish in dev mode (but not in prod)

**Comment by rYsvelain** [comment]
I tried but it doesn't make any effect the snapshot is not fired

**Comment by OskarStark** [comment]
did you switch to master? at the top?

https://sonata-project.org/bundles/page/master/doc/reference/installation.html

**Comment by rYsvelain** [comment]
Sorry I updated my comment. Maybe we should put the %kernel.debug% state in the sandbox project ?

**Comment by OskarStark** [comment]
feel free to make a pr in the sanbox :+1:

**Comment by rYsvelain** [comment]
Thank you for the support

**Comment by OskarStark** [comment]
welcome :+1:
