### ISSUE TITLE
Branch 2.3 is broken

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataPageBundle#614]
Maybe we need a backport?

**Comment by Th3Mouk** [comment]
@core23 what i broken tests or functionnal ? Cause i've try to fix the tests but without success

**Comment by core23** [comment]
Have a look at https://travis-ci.org/sonata-project/SonataPageBundle/branches

**Comment by greg0ire** [comment]
Woops, I'm on it. At least the doc is broken, that's what I'm trying to fix.

**Comment by greg0ire** [comment]
Looks like it's not just about docs. Was this fixed in master?

**Comment by core23** [comment]
Master is green, but I have no idea / time what should be backported.
