### ISSUE TITLE
Unique Url validation not called

### ISSUE THREAD

**Issue by Th3Mouk** [sonata-project/SonataPageBundle#616]
I'm investigating on the Url generation what is wrong.

It's necessary to generate 2 snapshots of the page after changing the slug, to get the new url.

It's due to function fixUrl() on `PageManager` that she's only called during the snaping phase, and not during the edit of the page.

fixUrl() is called during the validation of the page edit, in the `Constraints\UniqueUrl` who is a class constraint, but seems not called.

Anyone has a clue how to proceed effectively ?

**Comment by Th3Mouk** [comment]
ping @OskarStark @greg0ire @core23

**Comment by greg0ire** [comment]
Sorry, I don't know that much about the page bundle. Constraints are called during validation, so I think you should have a look at how and whether validation is done when editing the a page.

**Comment by OskarStark** [comment]
to be honest, i don't know something about that.

@core23 you?

**Comment by core23** [comment]
Tested against the latest bundle versions... Everythink looks okay to me. I generated one new snapshot: the old link isn't accessible anymore the new link exist.

**Comment by Th3Mouk** [comment]
@core23 the problem was on 2.3, have a look on the creation of a page. When you're doing the first snapshot the slug stay empty.
I'm no longer supporting 2.3, so i can probably close it.
