### ISSUE TITLE
Error The child node "multisite" at path "sonata_page" must be configured.

### ISSUE THREAD

**Issue by Spartacus2018** [sonata-project/SonataPageBundle#618]
hello i have this error :

```
 [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  The child node "multisite" at path "sonata_page" must be configured.
```

so i start a frech symfony install :

> symfony new my_project_demoSonata 2.7
> php composer.phar require sonata-project/page-bundle --no-update
> php composer.phar require sonata-project/doctrine-orm-admin-bundle --no-update
> php composer.phar update

add this to appkernel.php

```
<?php
// app/appkernel.php
public function registerbundles()
{
    return array(
        // ...
        new Sonata\PageBundle\SonataPageBundle(),
        // ...
    );
}
```

after this i dot he new application bundle : 

`root [/var/www/sonata-demo/my_project_demoSonata] > php app/console sonata:easy-extends:generate SonataPageBundle

  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  The child node "multisite" at path "sonata_page" must be configured.
`

i follow the official documentation :  https://sonata-project.org/bundles/page/2-2/doc/reference/installation.html

can u tell me what i missing ?

thanks all

**Comment by V1TA5** [comment]
Had the same issue. 
Solved it by adding the config.yml options first and then doing composer update
its looking for:
sonata_page:
    multisite: host

**Comment by jordisala1991** [comment]
This docs talk about multihost option already : https://sonata-project.org/bundles/page/3-x/doc/reference/installation.html

Closing, if you think this is still an issue, please ping me to reopen with more details about the problem.
