### ISSUE TITLE
Shared blocks not cacheable

### ISSUE THREAD

**Issue by mlueck88** [sonata-project/SonataPageBundle#621]
Shared blocks are rendered via the  SonataPageBundle/Resources/views/Block/block_shared_block.html.twig template which itself uses the sonata_block_render helper. However this helper does not set the cache keys 'manager' and 'page_id' (and neither can the 'sonata_page_render_block' helper from PageExtension.php since $block->getPage() is null).

Therefore the BlockEsiCache throws due to missing cache keys (it always assumes that a block has a page).

However we cannot use the VarnishCache from SonataCache directly (cache: sonata.cache.esi instead of cache: sonata.page.cache.esi) as the shared block cannot generate cache keys itself. Trying to cache it then just results in a "Please define a controller key" exception when as ESI url is generated.

The PageExtension.php could be changed as follows:

``` php
        /**
         * @param PageBlockInterface $block
         * @param array              $options
         *
         * @return string
         */
        public function renderBlock(PageBlockInterface $block, array $options = array())
        {
            if ($block->getEnabled() === false && !$this->cmsManagerSelector->isEditor()) {
                return '';
            }

            // NEW CODE START //////////
            $manager = null;
            $page = null;
            if ($block->getPage() != null)
            {
                $page = $block->getPage();
            }
            else
            {
                $page = $this->cmsManagerSelector->retrieve()->getCurrentPage();
            }
            $manager = $block->getPage() instanceof SnapshotPageProxy ? 'snapshot' : 'page';
            // NEW CODE END //////////

            // CHANGES START //////////
            // defined extra default key for the cache
            $pageCacheKeys = array(
                'manager'   => $manager, // $page instanceof SnapshotPageProxy ? 'snapshot' : 'page'
                'page_id'   => $page->getId(), // $block->getPage()->getId(),
            );
            // CHANGES END //////////

            // build the parameters array
            $options = array_merge(array(
                'use_cache'        => isset($options['use_cache']) ? $options['use_cache'] : true,
                'extra_cache_keys' => array()
            ), $pageCacheKeys, $options);

            // make sure the parameters array contains all valid keys
            $options['extra_cache_keys'] = array_merge($options['extra_cache_keys'], $pageCacheKeys);

            return $this->blockHelper->render($block, $options);
        }
```

The shared block could then be rendered via sonata_page_render_block(sharedBlock) in block_shared_block.html.twig even when cached.

**Comment by Kaijiro** [comment]
Pretty much related, I can not add any Shared Block inside my pages because `block.page` is defined to null inside those blocks, so in `block_base.html.twig`, `block.page is defined ` returns `true` but `block.page.id` throws this Exception : 
`Impossible to access an attribute ("id") on a null variable in SonataPageBundle:Block:block_base.html.twig at line 23.`
