### ISSUE TITLE
Error pages not created

### ISSUE THREAD

**Issue by bilougit** [sonata-project/SonataPageBundle#627]
``` YAML
# config.yml
sonata_page:
    catch_exceptions:
        not_found: [404]
        fatal:     [500]
```

I run   `$ app/console sonata:page:update-core-routes` but no error route is created !

```
$ composer -i | grep -i sonata

sonata-project/admin-bundle              2.3.10             Symfony SonataAdminBundle
sonata-project/block-bundle              2.2.13             Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/cache-bundle              2.2.5              This bundle provides caching...
sonata-project/classification-bundle     2.2.x-dev fe3edca  Symfony SonataClassification...
sonata-project/core-bundle               2.3.10             Symfony SonataCoreBundle
sonata-project/datagrid-bundle           dev-master 6e7940a Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 2.3.3              Symfony Sonata / Integrate D...
sonata-project/easy-extends-bundle       2.1.10             Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.4.1              Lightweight Exporter library
sonata-project/formatter-bundle          dev-master d0ab65b Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2              Library to integrate Google ...
sonata-project/intl-bundle               2.2.4              Symfony SonataIntlBundle
sonata-project/media-bundle              2.3.3              Symfony SonataMediaBundle
sonata-project/news-bundle               2.3.5              Symfony SonataNewsBundle
sonata-project/notification-bundle       2.3.3              Symfony SonataNotificationBu...
sonata-project/page-bundle               2.3.9              Symfony SonataPageBundle
sonata-project/seo-bundle                1.1.10             Symfony SonataSeoBundle
sonata-project/user-bundle               2.2.4              Symfony SonataUserBundle
```

**Comment by Neodork** [comment]
The error routes are not generated with update-core-routes. Only those for the Page Admin (Page editor):

```cli
  UPDATE  sonata_page_exceptions_list                        /exceptions/list
  UPDATE  sonata_page_exceptions_edit                        /exceptions/edit/{code}
```

The error pages are only available in production mode. Developer mode provides links like:

```
yourdomain.com/exceptions/edit/404
yourdomain.com/exceptions/edit/500
```

**Comment by core23** [comment]
Maybe someone could supply a PR to create error pages too with this command?

**Comment by hug963** [comment]
I think that error pages are created automatically already:
https://github.com/sonata-project/SonataPageBundle/blob/3.x/Route/RoutePageGenerator.php#L159

I'm working on a new site and they did get generated.

**Comment by holivierhlg** [comment]
I actually face the same issue that OP. It's the second project where at first, the error pages are generated and shown in the list of page in the admin section and I could edit them at the time. 

But for some reason now that my project is almost over and I want to customize these pages, they don't appear anymore, and the console command won't do anything to solve that.

**Comment by holivierhlg** [comment]
I faced the same issue with two projects : error pages are generated at first but later I can't see them anymore.

Actually there is no issue : these pages have been created, but in the admin section, admin/sonata/page/page/list automatically redirect me to admin/sonata/page/page/tree, and with the tree view you cannot see the error pages.

You have to be in "list" view to see them.

**Comment by Avtonom** [comment]
@holivierhlg how to make the router work? I have given to the standard symfony plug 404.
No route found for "GET /ffff"
No route found for "GET /app.php/ffff"
No route found for "GET /app_dev.php/ffff"

**Comment by holivierhlg** [comment]
@Avtonom In dev mod, you won't see the customized 404 and 500 errors since the symfony debugger will be triggered instead.

Do you really get a "no route found" in prod ?

**Comment by Avtonom** [comment]
@holivierhlg Thank you! really only works in PROD mode. What is not very convenient because It is not possible to test on DEV machine. How to override the sonata.page.kernel.exception_listener failed.

**Comment by onatus** [comment]
Hello guys! Maybe someone knows how to use them? Because I've tried to configure them in prod and see only symfony error pages instead of created and setup sonata error pages.

**Comment by grekpg** [comment]
I have same sitation, error pages is not created, get 

`An exception has been thrown during the rendering of a template ("None of the chained routers were able to generate route: Route 'sonata_page_exceptions_list' not found").`
