### ISSUE TITLE
None of the chained routers were able to generate route: Route 'admin_sonata_page_page_create' not found

### ISSUE THREAD

**Issue by speeeeeed2006** [sonata-project/SonataPageBundle#631]
Hello, 
I try to add sonataPageBundle to my exisiting project to manage the content of some page. 
I followed the installation procedure to install all the required bundle, but I have an error after configuring the SonataPageBundle 
I looked the log and the main problem is 
```
("None of the chained routers were able to generate route: Route 'admin_sonata_page_page_create' not found") in "SonataAdminBundle:Block:block_admin_list.html.twig" at line 39. [] []
```
so it can't found the rout for "admin_sonata_page_page_create" I tried to found it but no existence of this route. 
I commented the code which call this route, I  also observed another error for a route about "list" I haven't search more because it was probably the same kind of error. 
So can someone explain to me the real error I made maybe or a way to fix this. 
Thank you.

**Comment by greg0ire** [comment]
Have you checked the output of `app/console router:debug` ?

**Comment by speeeeeed2006** [comment]
No it wasn't present.

**Comment by speeeeeed2006** [comment]
I have finally installed it. 
Don't use 2.3.6 instead use 2.3.9
If you need more details just ask me. I will try to explain it more next time.

**Comment by Neodork** [comment]
@speeeeeed2006 Would you be so kind to close the issue if you feel like it is resolved.
