### ISSUE TITLE
Root and parent Question

### ISSUE THREAD

**Issue by finchen** [sonata-project/SonataPageBundle#632]
Hi,

I have a question regarding the structure of the Page.
I am wondering if it is mandatory to have only one root page and if any other page should have a parent.

+ root (/)
++ page
++ page 2

or if it is possible to have a page 'outside' the root

+ root (/)
++ page
++ page 2
+ systempage

I am looking at having a menu builder which will build a menu with all the pages under the 'root'.
It seems there is no issue but the command:
  sonata:page:update-core-routes

forces to have a parent
   if (!$page->getParent() && $page->getId() != $root->getId()) {
       $page->setParent($root);
    }
https://github.com/sonata-project/SonataPageBundle/blob/master/Route/RoutePageGenerator.php#L145

Could a contributor tell me if it should be ok or not?
If yes, maybe i could add an option for the command.

Thanks
https://groups.google.com/forum/#!topic/sonata-devs/NuthvL6kkRY

**Comment by finchen** [comment]
it is actually used for the breadcrumb:
Home > Page

I have added a boolean field `onMainMenu` on Page for now.
i will see later how to let the user build a menu

**Comment by OskarStark** [comment]
@finchen you are right, we need to implement a possibility to add pages to differrent menus

ping @vworldat
