### ISSUE TITLE
BC break because of tree view

### ISSUE THREAD

**Issue by Neodork** [sonata-project/SonataPageBundle#638]
The following code is BC break with Sonata Admin Bundle and Sonata Block Bundle introduced by 
2fbd2e105f70c5bc1d1e48292ccbeb595527b9a2. Linked entities (with `sonata_type_model_list` form type) in blocks or admins now go to the Tree view page as default. The tree page however has no "Select" feature and a click on the name redirects to the edit page admin menu.

Note: Did not test admin, did test blocks.

``` php
   //PageAdminController.php

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function listAction()
    {
        if (!$this->getRequest()->get('filter')) { // <--- BC break
            // Redirects us to tree view, tree view has no SELECT feature
            return new RedirectResponse($this->admin->generateUrl('tree'));
        }

        return parent::listAction();
    }
```

Not sure what to do with it, what does Sonata think of this? @core23

**Comment by OskarStark** [comment]
for know it looks as a BC break to me, too!

**Comment by Neodork** [comment]
@core23 Should I separate https://github.com/sonata-project/SonataAdminBundle/issues/3863 from this issue? They are not fully the same. Because even when the filtering is fixed the ``sonata_type_model_list`` will still not be able to operate with the treeview as default.

So I was thinking keep the filter in the code. Then filtering can be fixed in https://github.com/sonata-project/SonataAdminBundle/issues/3863 and we will have the ``sonata_type_model_list`` functionality working.

Your thoughts?

**Comment by core23** [comment]
We should fix the admin issue first and test, if this will (partial) solve the other issue. After that we could have a look at this bundle.
