### ISSUE TITLE
Can't install Bundle on Symfony 3

### ISSUE THREAD

**Issue by Id4v** [sonata-project/SonataPageBundle#668]
When trying to install SonataPageBundle 3.0.0 on Symfony 3.1.0 you get an error saying that there is a version conflict on the symfony/options-resolver package.

Symfony requires a 3.1.0 version whereas SonataPageBundle asks for a ^2.3

| Question | Answer |
| --- | --- |
| Bundle version | 3.0.0 |
| Symfony version | 3.1.0 |
| php version | 5.6.22 |
# Error message

``` bash
Problem 1
    - Installation request for sonata-project/page-bundle ^3.0 -> satisfiable by sonata-project/page-bundle[3.0.0].
    - Conclusion: remove symfony/symfony v3.1.0
    - sonata-project/page-bundle 3.0.0 requires symfony/options-resolver ^2.3
```
# Steps to reproduce

Create new Symfony Project based on 3.x.
Follow SonataPageBundle docs to install last stable.
Launch `composer update`
# Expected results

SonataPageBundle installs correctly
# Actual results

SonataPageBundle doesn't install and can't be used.

**Comment by core23** [comment]
@Soullivaneuh Is there any reason why we don't support symfony3? The travis tests (in devkit) are only running against the symfony2 releases.

**Comment by Soullivaneuh** [comment]
@core23 @Id4v Simply because this bundle is not compatible because of `symfony-cmf/routing-bundle` sub-dependency.

```bash
sullivan@sweethome:~/projects/fork/sonata-project/SonataPageBundle(3.x)$ composer why-not -t 'symfony/http-kernel:3'
symfony/symfony v2.8.6 The Symfony PHP framework
├──sonata-project/page-bundle 3.9999999.9999999.9999999-dev (requires symfony/validator ^2.3) (circular dependency aborted here)
└──symfony-cmf/routing-bundle 1.4.0 (requires symfony/framework-bundle ~2.3)
   └──sonata-project/page-bundle 3.9999999.9999999.9999999-dev (requires symfony-cmf/routing-bundle ^1.1)
```

**Comment by jaxel87** [comment]
symfony-cmf/routing-bundle: 2.0.x-dev 
requires: symfony/framework-bundle: ^2.8|^3.0

**Comment by Soullivaneuh** [comment]
@jaxel87 `symfony-cmf/routing-bundle` 2.0 is not stable yet, we would not implement it now.

**Comment by brunocombodo** [comment]
I would be nice to create a `sonata-project/page-bundle: x-dev` version pointing to `symfony-cmf/routing-bundle: 2.0.x-dev`  in order to begin the use of this bundle using symfony 3

**Comment by greg0ire** [comment]
This might be resolved soon, see [this thread](https://github.com/symfony-cmf/symfony-cmf/issues/235)

**Comment by comnuoc** [comment]
Please update to support Symfony 3. Thanks.

**Comment by greg0ire** [comment]
See #810
