### ISSUE TITLE
Page and Snapshot URL not generated

### ISSUE THREAD

**Issue by Id4v** [sonata-project/SonataPageBundle#669]
When creating a new page the url is not generated unless you publish it twice.

| Question       | Answer
|----------------|-------------------------------
| Bundle version | 2.3.10
| Symfony version| 2.7.14
| php version    | 5.6.22

# Error message

```
No Message
```

# Steps to reproduce
Create a new page.
Give it a name => "My new page"
Validate creation. => no URL

Go to create a Snapshot of this page.
Validate creation and go back to Snapshot List => No URL --> Page not accessible
Publish another snapshot of this new page => Url gets generated --> Page is accessible

# Expected results

URL gets generated on first snapshot creation, maybe even on Page Creation?

# Actual results

URL is generated on the second snapshot creation.

**Comment by core23** [comment]
Can you try the latest 3.0 release, we don't support the old 2.x branch.

**Comment by Soullivaneuh** [comment]
Pleas reopen an issue if this can be reproduced on 3.x.
