### ISSUE TITLE
SonataDataGrid Bundle version update 

### ISSUE THREAD

**Issue by srinikumar11** [sonata-project/SonataPageBundle#715]
Hi there,

There was an issue in updating  SonataPageBundle due to SonataDataGridBundle ~2.2@dev version unavailable which is used in PageBundle 2.x versions. Can this be updated in latest PageBundle 2.x versions.

Thanks,
Srini

**Comment by greg0ire** [comment]
Hi, sorry but as you may already know, Sonata 2 is no longer supported. Please ask us to reopen if you still experience this with Sonata 3.

**Comment by core23** [comment]
@rande  What about a short blog article with the new supported versions?

**Comment by rande** [comment]
@core23 we clearly need to communicate more on the sonata website, your topic is important, but there are so much to say since a few months! Thanks to @sonata-project/contributors
