### ISSUE TITLE
shared block compose editing error

### ISSUE THREAD

**Issue by n3o77** [sonata-project/SonataPageBundle#741]
### Environment
Ubuntu Trusty 14.04 PHP 5.6

#### Sonata packages

```bash
sonata-project/admin-bundle              3.1.0  The missing Symfony Admin Generator
sonata-project/block-bundle              3.2.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/cache-bundle              2.3.1  This bundle provides caching services
sonata-project/classification-bundle     3.1.0  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.1.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2    Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.0.5  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0  Lightweight Exporter library
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.2.4  Symfony SonataIntlBundle
sonata-project/media-bundle              3.3.0  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.0.0  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.1.0  This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.0.2  Symfony SonataSeoBundle
sonata-project/translation-bundle        2.0.2  SonataTranslationBundle
sonata-project/user-bundle               3.1.0  Symfony SonataUserBundle
```

#### Symfony packages

```bash
symfony/assetic-bundle     v2.8.0  Integrates Assetic into Symfony2
symfony/filesystem         v3.1.6  Symfony Filesystem Component
symfony/monolog-bundle     2.12.0  Symfony MonologBundle
symfony/phpunit-bridge     v2.8.13 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.2.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.2.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.2.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.4.0  Symfony SwiftmailerBundle
symfony/symfony            v2.8.13 The Symfony PHP framework
```

#### PHP version

```bash
PHP 5.6.25-1~dotdeb.7.1 (cli) (built: Aug 19 2016 03:15:37) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

## Subject

I've created a shared block and try to use it in the compose view. But when adding it to a section the request fails with: The option "blockId" does not exist. Defined options are: "template".

The block was actually added, but it's not deletable nor editable after a reload.
<img width="828" alt="Result after reload and hitting 'add' 3 times" src="https://cloud.githubusercontent.com/assets/321891/20141644/90fb8f1e-a691-11e6-84f7-b59ff027cf65.png"> (Result after reload and hitting 'add' 3 times)

When adding the 'blockid' entry to https://github.com/sonata-project/SonataPageBundle/blob/3.x/Block/SharedBlockBlockService.php#L127-L129 it solves the problem. I'm not sure if this will have other side effects and if this is the right approach. If so please let me know and i'll create a PR.

**Comment by Matan** [comment]
Getting same error. The fix works for me.

**Comment by OskarStark** [comment]
@core23 can you help?

**Comment by n3o77** [comment]
@Matan my fix looks like this, so you don't have to change the source of a dependency:

```php
<?php

namespace AppBundle\Block;

use Sonata\PageBundle\Block\SharedBlockBlockService;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SharedBlock extends SharedBlockBlockService {

    /**
     * {@inheritdoc}
     */
    public function configureSettings(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'template' => 'SonataPageBundle:Block:block_shared_block.html.twig',
            'blockid' => '',
            'blockId' => '',
        ));
    }

}
```
Both variants of `blockid` are required.
services:
```yml
services:
    sonata.page.block.shared_block:
        class: AppBundle\Block\SharedBlock
        arguments: ["Shared Block", "@templating", "@service_container", "@sonata.page.manager.block"]
        tags:
            - { name: sonata.block }
```

**Comment by OskarStark** [comment]
@n3o77 could you provide a PR with a patch?

**Comment by n3o77** [comment]
@OskarStark sure. I'll take some time to figure out why there are 2 variants of the `blockId` key. Should be unified. Will send a PR by the end of the week.

**Comment by Matan** [comment]
Thanks guys, I managed to override class the using the `CompilerPassInterface` as a temporary solution.

**Comment by OskarStark** [comment]
> @OskarStark sure. I'll take some time to figure out why there are 2 variants of the blockId key. Should be unified. Will send a PR by the end of the week.

Thank you @n3o77 👍

**Comment by n3o77** [comment]
@OskarStark only had to add `blockId`. The other variant came from an old Database entry.

**Comment by greg0ire** [comment]
How did this work before, and why did it stop working? Does it have to do with `blockId` vs `blockid` somehow?

**Comment by greg0ire** [comment]
Here is the inheritance chain for anyone who wants to take a look : 

Sonata\PageBundle\Block\SharedBlockBlockService
 -> 
Sonata\BlockBundle\Block\BaseBlockService
 -> 
Sonata\BlockBundle\Block\Service\AbstractAdminBlockService
->
Sonata\BlockBundle\Block\Service\AbstractBlockService

**Comment by n3o77** [comment]
@greg0ire the `blockId` vs `blockid` thing is probably only related to me testing at the time and then forgetting about removing it from the database.

I don't know how it was supposed to work without the setting. But only occurred when editing the shared block, i assume that's because only then the optionsResolver [here](https://github.com/sonata-project/SonataPageBundle/blob/3.x/Admin/BaseBlockAdmin.php#L245) is used which first checks if the setting exists or not. When creating a new one it seems it only uses the setSetting option on the [block](https://github.com/sonata-project/SonataBlockBundle/blob/3.x/Model/BaseBlock.php#L138-L141) which doesn't seem to validate agains the settings. But tbh, i'm just not deep enough in the code to be 100% sure about it, so i might miss something.

**Comment by greg0ire** [comment]
Oh right, so what you're saying is… it never worked ^^ Makes sense if this is not the main use case.

**Comment by greg0ire** [comment]
If you feel up to it, use `git bisect` on the page bundle and find the commit that breaks this.

**Comment by greg0ire** [comment]
Oh I think I understood! Look at [this line](https://github.com/sonata-project/SonataPageBundle/blob/3.x/Admin/BaseBlockAdmin.php#L246). Then look at [the last line of the 2.6.0 changelog](https://github.com/symfony/options-resolver/blob/master/CHANGELOG.md#260)

**Comment by Wharenn** [comment]
Yes, the blockId option is missing in the configureSettings. We introduced shared block concept as part of a work in a side project and then we used a block service which inherited Sonata's ``SharedBlockBlockService``. The blockId option was defined by mistake in the child class instead of the Sonata one.

**Comment by greg0ire** [comment]
Thanks for clarifying this @Wharenn , we can safely merge then.
