### ISSUE TITLE
Hybrid Page

### ISSUE THREAD

**Issue by finchen** [sonata-project/SonataPageBundle#752]
Hi,

I am using **Dynamic Page** for a list of **category**.
the route:
```yml
category:
    path:     /category/{slug}
    defaults: 
        _controller: MyBundle:Category:index
        slug: all
```

with `php bin/console sonata:page:update-core-routes --site=all`

it will generate the route as a Dynamic Page in the database
```
Page.route_name = category
Page.url = /category/{slug}
Page.template = default
```

In most cases, this is enough:
- I can choose a template and add blocks for the category pages (all the same)
- I can set the page title and meta description from the controller for each category

Limitations:
- I can not customize one category from the CMS (eg. add blocks for `T-Shirt` or let the CMS user change the title)
- The drop down of Pages (eg. 'redirect' or 'parent' from the Page Admin) contains only the CMS page
- If I build a 'menu builder' or a ck editor plugin to link to a page, the category pages don't really exist

Ideas:
- when selecting a Dynamic Page should a second dropdown appear with the possible 'parameters' (eg. all the category)? it seems difficult to implement
- should it use the CMF routing to generate all the pages and store them? (eg. for category. for 10000 products it might not be ideal)

Just looking for feedback first.
Thank you
(let me know if you would prefer to move it to stackoverflow)

**Comment by grimpows** [comment]
i just start to take a real look on the sonata page bundle, actually i got
a prob, blocks inst set to my page (header, content_top ....) and i didnt
find why yet, but, i already thinked about customize, the first thing i
already did is to add parameter attribute to a page, create a parameter
bundle, and add it attribute with special fonctionallity, for exemple, when
you render the title of a page, you will be able to look if parameter.name
is set, if not, set default title :) that really easy to implement, just
create parameter bundle, create parameter entity, do a oneToOne
unidirectional mapping from page->parameter to ParameterBundle:Parameter,
override the pageAdmin, add parameter in formMapper :)

2016-12-01 21:09 GMT+01:00 finchen <notifications@github.com>:

**Comment by jordisala1991** [comment]
I think that those ideas are too specific to be implemented directly on this bundle.

Closing for now, maybe this should be a question on stackoverflow on how to do it outside sonata.

If @sonata-project/contributors or you think that this should be implemented or have an idea on how to do it, please ping me to reopen.
