### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by bruno-ds** [sonata-project/SonataPageBundle#753]
Hello,

Being new to sonata & symfony, I'm following the documentation.

Here is the feedback I can give you as a newbie: 

- security sections ([link one ""](https://sonata-project.org/bundles/page/3-x/doc/reference/installation.html#configuration), [link two](https://sonata-project.org/bundles/page/3-x/doc/reference/getting_started.html#add-or-edit-a-block))
  - in the link one, the doc make us add role, but no firewall, so the config is incomplete
  - in the link two, if I understand well, the doc need a firewall installed in order to have a registered user
  - improvement : give a sample conf, why not with an in_memory + plain text password user list

- page composer
  - the given configuration fail (see [this issue](http://stackoverflow.com/questions/40767999/sonatapagebundle-no-container-defined-for-matrix-area-header) for example)
  - improvement : give a non failing conf. or the explanations of how to correct it

- general use of the admin : this aspect is not covered,
  - for example, the icons in the admin are not explained
  - for example, the creation of a new page isn't covered (an example would be welcomed)
    - for the "edit page"
    - for the "composer"
    - for the "block list" and subsequent entries

I have to admin that while your doc is really great, and the project is really apealing, the doc. it do not cover everything, and i feel terribly lost, so lost that maybe, i'll give ezplateform a try.

PS : I encountered several problems during my install, notably : 
- [the sandbox install fail](https://github.com/sonata-project/sandbox/issues/561#issuecomment-264899038) => I moved to install the admin bundle then the page bundle
- [sonata admin bundle is not compatible with symfony 3.2](https://github.com/sonata-project/SonataAdminBundle/pull/4216) i switched to the 3.1 (maybe the doc could mention this limitation)
- [sonata page bundle is not compatible with symfony 3.1](https://github.com/sonata-project/SonataPageBundle/issues/668) I switched to the 2.8 (maybe the doc could mention this limitation)
- the [add or edit a block](https://sonata-project.org/bundles/page/3-x/doc/reference/getting_started.html#add-or-edit-a-block) section refer to nonexistent blocks : `page_include_stylesheets` and `page_include_javascripts `

best regards and thanks for your great work!

**Comment by greg0ire** [comment]
Lots of good ideas here. We don't get many documentation contributions, would you like to contribute some of your propositions?

**Comment by brunocombodo** [comment]
I'd like I could, but I'm not competent enough, sorry.

**Comment by greg0ire** [comment]
Well now you know why the documentation is not that good.

**Comment by greg0ire** [comment]
I wrote [a guide for contributing to the docs](https://github.com/sonata-project/SonataPageBundle/blob/3.x/CONTRIBUTING.md#the-documentation) recently, maybe it will change your mind?

**Comment by bruno-ds** [comment]
Great doc. it's really interesting to read about all these subjects.
I think that you've achieved to be not too short, not too long.

(For me it is too late for the moment, my projects has moved to others seas, maybe I'll come back later ;) )

**Comment by greg0ire** [comment]
Thanks :)
