### ISSUE TITLE
hide_disabled_blocks option not working as expected

### ISSUE THREAD

**Issue by mgrundkoetter** [sonata-project/SonataPageBundle#756]
### Environment
```
sonata_page:
    direct_publication: true
    multisite: host
    hide_disabled_blocks: true
```
#### Sonata packages

```bash
$ composer show sonata-project/*

sonata-project/admin-bundle              3.10.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.2.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/cache-bundle              2.3.1  This bundle provides caching services
sonata-project/classification-bundle     3.1.0  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.1.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2    Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.1  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0  Lightweight Exporter library
sonata-project/formatter-bundle          3.0.1  Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.2.4  Symfony SonataIntlBundle
sonata-project/media-bundle              3.3.0  Symfony SonataMediaBundle
sonata-project/news-bundle               3.0.0  Symfony SonataNewsBundle
sonata-project/notification-bundle       3.0.0  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.2.0  This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.0.2  Symfony SonataSeoBundle
sonata-project/user-bundle               3.2.0  Symfony SonataUserBundle
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     2.12.0  Symfony MonologBundle
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.4.0  Symfony SwiftmailerBundle
symfony/symfony            v2.8.14 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 5.6.29 (cli) (built: Dec 12 2016 10:16:18) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

## Subject
When I create a site, a page and some content elements (e.g. type rich text), all of them are rendered in the frontend, even if some are set to "deactivated" (enable=0 in db) and hide_disabled_blocks is set to true.

## Steps to reproduce
* create site
* create cms page for this site
* create some content elements (blocks) on the page
* hide at least one of them
* create publication (our config is with auto publish, but makes difference)

## Expected results
The blocks which have been set to disabled in backend, should not be visible in frontend after next publication.

## Actual results
All blocks (content) on the page are shown, even if deactivated  and hide_disabled_blocks=true in sonata_page yml conf (this option is not documented, btw).

**Comment by mgrundkoetter** [comment]
Narf. This, in fact, IS WORKING actually. I was logged in as editor all the time, so the blocks are ALWAYS shown, ignoring all the settings. This is very confusing anyway. When you are working on a content page, you usually are previewing the result in another browser tab. But as long as you are logged in, the deactivated elements are still showing up. As soon as you log out, it's as expected. So maybe the "fix" could be a) documenting the feature, b) show some "hint" in frontend that certain blocks are only visible because the user is logged in as editor.

**Comment by greg0ire** [comment]
Would you like to provide a PR for a) and/or b) ?

**Comment by gremo** [comment]
I can confirm this is really confusing. IMHO blocks should be hidden even to editors, I can work to a PR if you agree.

**Comment by greg0ire** [comment]
But then you can't preview them anymore, can you?

**Comment by gremo** [comment]
Yes but I can see this as an issue: editors want to see the final result (without using incognito or another browser)  and can re-enable the block at any time. Let me know, thanks.

**Comment by greg0ire** [comment]
@mgrundkoetter , what do you think?

**Comment by mgrundkoetter** [comment]
Hm, from the editor perspective I agree with @gremo The editors should by default only see the enabled blocks, even if logged in. Maybe it's possible to introduce a parameter, cookie or something to get into the other mode and see all the blocks. Maybe it's possible to add a button into the backend somewhere to switch between those "modes". (which sets cookie in background which is then evaluated when rendering the page?)

**Comment by gremo** [comment]
I would not over-complicate this. One idea could be changing the `hide_disabled_blocks ` configuration option from boolean to string type, into something like this:
- `all`
- `all_but_editor`
- `never`

BC transforming `true` to `all_but_editor` or `false` to 'never'. I would choose `all` ;-)

**Comment by mgrundkoetter** [comment]
Hm, easy solution, but any editor is able to change it then himself without editing the yml config. 
But anyway, I guess it is ok for most applications, at least in my project it would be fine for the customer to choose one setting and stick with it. BTW, I would propose to stay consistent with the wording. "all" and "never" don't really fit :-)

**Comment by gremo** [comment]
Yeah I know, it was just an idea. Not my mother tongue by the way :-)

**Comment by jorenvh1** [comment]
Anyone working on this?
