### ISSUE TITLE
Correct lazy loading

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataPageBundle#775]
While using phpstan, I stubled upon multiple collections that uses lazy loading.

https://github.com/sonata-project/SonataPageBundle/blob/f48a2b7c17740697e30bf5f15e20a300e9870f75/Model/Block.php#L65
https://github.com/sonata-project/SonataPageBundle/blob/c1cfa5ff41df9b380fbd8ce14b042183cb1204b6/Model/Page.php#L676
https://github.com/sonata-project/SonataPageBundle/blob/c1cfa5ff41df9b380fbd8ce14b042183cb1204b6/Model/Page.php#L683

Not sure if this is the right way today. Looking in the offical [doctrine docs](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/extra-lazy-associations.html) showed another way.

Anyone using lazy loading in PHP and can confirm that?

**Comment by VincentLanglet** [comment]
Solved in 4.x
