### ISSUE TITLE
Add block of type, the (+) button redirects to 'admin/sonata/page/page/5/block/create?composer=1'

### ISSUE THREAD

**Issue by Nabilcnpe** [sonata-project/SonataPageBundle#795]
hello guys, 
when i try to add a block of type "form" (for exemple) the add button (+) redirects me to the link mentioned above ! i can't tell if this is normal ! in all tuto i saw the add button display a block under in the same page !

Any idea please ? i can't tell if it's due to a bug or my configuration !

Thanks

**Comment by jordisala1991** [comment]
We cant tell either without more info.

Closing because this is almost a year old. If you still having this issue, please ping me with more information and I will reopen
