### ISSUE TITLE
Page admin doesn't work anymore, serious exception is thrown in edit and create route

### ISSUE THREAD

**Issue by gremo** [sonata-project/SonataPageBundle#803]
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.16.0
sonata-project/block-bundle              3.3.2
sonata-project/cache                     1.0.7
sonata-project/cache-bundle              2.3.1
sonata-project/classification-bundle     3.3.0
sonata-project/core-bundle               3.2.0
sonata-project/datagrid-bundle           2.2.1
sonata-project/doctrine-extensions       1.0.2
sonata-project/doctrine-orm-admin-bundle 3.1.4
sonata-project/easy-extends-bundle       2.1.10
sonata-project/exporter                  1.7.1
sonata-project/formatter-bundle          3.2.1
sonata-project/google-authenticator      1.0.2
sonata-project/intl-bundle               2.3.0
sonata-project/media-bundle              3.5.1
sonata-project/notification-bundle       3.1.0
sonata-project/page-bundle               3.4.1
sonata-project/seo-bundle                2.1.0
sonata-project/translation-bundle        2.1.1
sonata-project/user-bundle               3.2.3
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.1
symfony/monolog-bundle     v3.1.0
symfony/phpunit-bridge     v2.8.19
symfony/polyfill-apcu      v1.3.0
symfony/polyfill-intl-icu  v1.3.0
symfony/polyfill-mbstring  v1.3.0
symfony/polyfill-php54     v1.3.0
symfony/polyfill-php55     v1.3.0
symfony/polyfill-php56     v1.3.0
symfony/polyfill-php70     v1.3.0
symfony/polyfill-util      v1.3.0
symfony/security-acl       v3.0.0
symfony/swiftmailer-bundle v2.5.4
symfony/symfony            v2.8.19
```

#### PHP version

```bash
$ php -v
PHP 5.5.31 (cli) (built: Jan  6 2016 12:57:50)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

## Subject

Page admin doesn't work anymore, serious exception is thrown in edit and create route

## Steps to reproduce
Go in the page admin and add a new page (or edit an existing one).

## Expected results
The edit form is shown.

## Actual results
An exception is thrown:

> The options "choices", "choices_as_values", "choice_loader" have a cyclic dependency.
> 500 Internal Server Error - OptionDefinitionException
> in vendor\symfony\symfony\src\Symfony\Component\OptionsResolver\OptionsResolver.php at line 951

    // If the closure is already being called, we have a cyclic
    // dependency
    if (isset($this->calling[$option])) {
        throw new OptionDefinitionException(sprintf(
            'The options "%s" have a cyclic dependency.',
            implode('", "', array_keys($this->calling))
        ));

I can't find the source of this exception. But if you comment out the `parent` and `target `form fileds in `PageAdmin `class, the error goes away. Maybe is somethoing related to the `sonata_page_selector` type?

**Comment by greg0ire** [comment]
Related to [this](https://github.com/sonata-project/SonataAdminBundle/issues/4443) ?

**Comment by gremo** [comment]
@greg0ire thanks a lot. Do you know how to downgrade (and what) in order to fix this serious error? I have a site in production and need to fix this.

**Comment by greg0ire** [comment]
I don't know, sorry, didn't experience it myself

**Comment by gremo** [comment]
Closing as not related to this bundle.
