### ISSUE TITLE
Updating to 3.5.0 breaks new page creation

### ISSUE THREAD

**Issue by haivala** [sonata-project/SonataPageBundle#823]
#### composer.json
symfony 2.8 with
https://github.com/EntropyRy/Tunkki/blob/5e9fb61deb1a21a4de96f9bc8de17617383131e3/symfony/composer.json

#### PHP version

```bash
$ php -v
PHP 7.1.5 (cli) (built: May 13 2017 00:27:38) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.5, Copyright (c) 1999-2017, by Zend Technologies
```

## Steps to reproduce

1. Create new page
2. try to select parent page
3. update

## Expected results

parent page is valid and page is updated

## Actual results
parent page is not listed by names. It is listed by id's and after update is says
"The root URL '/' is already associated with another page of this site, please select a parent."

## quick fix

downgrade to pagebundle 3.4. compsoer says:
```
Package operations: 0 installs, 3 updates, 0 removals
  - Updating symfony-cmf/routing (2.0.1 => 1.4.1): Downloading (100%)         
  - Updating symfony-cmf/routing-bundle (2.0.0 => 1.4.0): Downloading (100%)         
  - Updating sonata-project/page-bundle (3.5.0 => 3.4.0): Downloading (100%) 
```
now everything is working again

**Comment by greg0ire** [comment]
Can you bisect this down to a particular commit?

**Comment by n3o77** [comment]
I have the same problem it's because of this: https://github.com/sonata-project/SonataPageBundle/commit/75266663e08622e80dfbd335eb46bfeadedc05dc#diff-4e0e2a6b89f4ebf82e5ce49e8bf45c4aL54

I changed it back to the SimpleChoiceList and it works again.

**Comment by greg0ire** [comment]
> parent page is not listed by names. It is listed by id's and after update is says

Oh I missed this when reading. I guess the choices should be flipped. Can any of you try `new ArrayChoiceList(array_flip($that->getChoices($opts)))` and report back?

**Comment by n3o77** [comment]
You can't flip the array as the values are objects and so not allowed as key.

**Comment by n3o77** [comment]
https://github.com/symfony/symfony/issues/14350

**Comment by greg0ire** [comment]
Ok so TL;DR : the solution would be to use `choices` instead of `choice_list`?

**Comment by n3o77** [comment]
I guess so, i tried to get it running with ArrayChoiceList but with no luck.

**Comment by greg0ire** [comment]
Can you try with `choices` and make a PR? I don't use this bundle, and cannot test properly.

**Comment by n3o77** [comment]
Sure, I can do that later today.

**Comment by greg0ire** [comment]
Thanks a lot!

**Comment by haivala** [comment]
Thank you for the work!
