### ISSUE TITLE
[bug] No create route on 3.5.0

### ISSUE THREAD

**Issue by Migo2468** [sonata-project/SonataPageBundle#826]
In version 3.5 when create new page on site route not created.
In Parent is only number, after is name page.
When we choose any parent we have error:

> "The root URL '/' is already associated with another page of this site, please select a parent."

![zaznaczenie_068](https://user-images.githubusercontent.com/3847457/27376235-d3d2ce20-5671-11e7-9c8c-e68bdedfbe3e.png)
![zaznaczenie_069](https://user-images.githubusercontent.com/3847457/27376236-d3dc61e2-5671-11e7-8a33-35b544a2a0e0.png)

**Solution**
Retreat to 3.4.1

**Comment by n3o77** [comment]
That's already fixed here #824

**Comment by greg0ire** [comment]
Thanks @n3o77 !
