### ISSUE TITLE
command sonata:page:clone-site doesn't work

### ISSUE THREAD

**Issue by Migo2468** [sonata-project/SonataPageBundle#827]
in Comand line when we use 

> sonata:page:clone-site --help

on input we have:

`[Symfony\Component\Console\Exception\LogicException]  
  An option with shortcut "s" already exists.           
                                                        

help [--xml] [--format FORMAT] [--raw] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> [<command_name>]`

**Comment by greg0ire** [comment]
Indeed. `--shell`. Can you make a PR to fix this?

**Comment by Migo2468** [comment]
When I add --shell is opened console Symfony but command sonata:page:clone-site is not working in console.

**Comment by greg0ire** [comment]
I know. I understand. That is because it defines a `-s` shortcut, that is already taken by `--shell`. Can you make a PR that just removes the shortcut from this command.

**Comment by jordisala1991** [comment]
Fixed already
