### ISSUE TITLE
Block disable not is hidden

### ISSUE THREAD

**Issue by Migo2468** [sonata-project/SonataPageBundle#836]
#### Symfony packages
sonata-project/admin-bundle              3.20.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/cache-bundle              2.3.1  This bundle provides caching services
sonata-project/classification-bundle     3.3.1  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.5  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/formatter-bundle          3.2.2  Symfony SonataFormatterBundle
sonata-project/google-authenticator      2.0.0  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.3.1  Symfony SonataIntlBundle
sonata-project/media-bundle              3.5.1  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.1.0  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.4.1  This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.2.0  Symfony SonataSeoBundle
sonata-project/timeline-bundle           3.1.1  Integrates SpyTimelineBundle into Sonata
sonata-project/translation-bundle        2.1.1  SonataTranslationBundle
sonata-project/user-bundle               3.2.4  Symfony SonataUserBundle

#### PHP version
PHP 7.0

## Subject

When disable block in admin panel. Block does not hidden in frontend.

## Steps to reproduce
Change BlockInteractor in line ~163 add line 
`if ($block->getEnabled() == false) continue;`

## Expected results
Hidden block in frontend.

**Comment by greg0ire** [comment]
Can you please make a PR?

**Comment by Migo2468** [comment]
Yes
