### ISSUE TITLE
[RFC] Change translation domain for block names

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataPageBundle#842]
Today we are using the `SonataPageBundle` as the translation domain for block name translation. This is not a good idea, because we need the [same translation](https://github.com/sonata-project/SonataPageBundle/blob/3.x/Resources/views/BlockAdmin/select_type.html.twig#L30) for the `SonataDashboardBundle` to get a localized block name.

Maybe we should change [this behavior](https://github.com/sonata-project/SonataPageBundle/blob/3.x/Resources/views/BlockAdmin/select_type.html.twig#L30) to use `SonataBlockBundle` as the translation domain, which looks more appropriate.

Example translation entry:
https://github.com/sonata-project/SonataPageBundle/blob/3.x/Resources/translations/SonataPageBundle.en.xliff#L838-L840

**Comment by greg0ire** [comment]
> because we need the same translation for the SonataDashboardBundle to get a localized block name.

I don't understand what you mean by that, can you explain?

**Comment by core23** [comment]
If you want to create a new page layout with blocks by using the admin page composer and haven't defined a translation domain for the block, the fallback is `SonataPageBundle` or `SonataDashboardBundle`, depending on the admin composer you are using

**Comment by greg0ire** [comment]
I don't understand why it depends on the admin composer or why you could have several of them, but now I get that the issue you want to avoid is having to create the same translation in several catalogs because you can't predict which one is going to be used, is that right?

**Comment by core23** [comment]
> you want to avoid is having to create the same translation in several catalogs because you can't predict which one is going to be used, is that right?

That's the problem. When we have a composer for blocks (e.g. sonata page layout composer or sonata dashboard composer) we have different default translation domains: `SonataPageBundle` and `SonataDashboardBundle`. 

Before creating the dashboard bundle, this was no problem. But when using this bundle we have this problem:
<img width="661" alt="bildschirmfoto 2017-08-01 um 18 18 03" src="https://user-images.githubusercontent.com/3440437/28835496-c74f4fcc-76e5-11e7-9ffe-fd3d0b2440ba.PNG">

**Comment by greg0ire** [comment]
Ok, I get now, and I agree with you on the solution, because `SonataBlockBundle` is a shared dep of both bundles, so they both know about it.
