### ISSUE TITLE
ACL system don't work properly

### ISSUE THREAD

**Issue by edwines** [sonata-project/SonataPageBundle#86]
In SPB only the super admin user can use all the features of the bundle... if some non super-admin user with the permissions EDITOR (or even with ADMIN permissions) try to work with the bundle, he must be has this issues:
- When he create a new page, it will not has access to edit it... the only way to assign the correct rights is running the command `app/console sonata:admin:generate-object-acl`... and this is a issue because the final user don't has access to the console.
- When you create some page snapshot, the controller redirect you after the operation and show a permissions error (even if the permission is assigned to the user)
- When some page has a parent, and the parent has the child as a target... the page cannot be edited for non super-admin use

**Comment by jordisala1991** [comment]
Seems working. Closing
