### ISSUE TITLE
Sonata page keeps redirecting to a redirection html page in between

### ISSUE THREAD

**Issue by codebach** [sonata-project/SonataPageBundle#921]
How can I configure to allow all redirections?

This  listener: https://github.com/sonata-project/SonataPageBundle/blob/3.x/src/Listener/ResponseListener.php#L93

Is it possible to add a `_sonata_page_skip` to request automatically for admin pages?

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
