### ISSUE TITLE
Snapshot generation command does not work anymore

### ISSUE THREAD

**Issue by psyray** [sonata-project/SonataPageBundle#950]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.x-dev 629f0c4    dev-master d1b6271 The missing Symfony Admin Generator
sonata-project/block-bundle              3.11.0             3.11.0             Symfony SonataBlockBundle
sonata-project/cache                     1.1.1              2.0.1              Cache library
sonata-project/cache-bundle              2.4.0              2.4.0              This bundle provides caching services
sonata-project/core-bundle               3.9.0              3.9.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1              2.3.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.4.1              3.4.1              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.4.0              2.4.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.8.0              1.8.0              Lightweight Exporter library
sonata-project/formatter-bundle          3.4.0              3.4.0              Symfony SonataFormatterBundle
sonata-project/media-bundle              3.10.1             3.10.1             Symfony SonataMediaBundle
sonata-project/notification-bundle       3.3.1              3.3.1              Symfony SonataNotificationBundle
sonata-project/page-bundle               3.7.1              3.7.1              This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.5.0              2.5.0              Symfony SonataSeoBundle
sonata-project/user-bundle               dev-master ff710b8 dev-master 4a549ad Symfony SonataUserBundle

```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/assetic-bundle     v2.8.2 v2.8.2 Integrates Assetic into Symfony2        
symfony/monolog-bundle     v3.1.2 v3.1.2 Symfony MonologBundle
symfony/phpunit-bridge     v3.4.3 v4.0.3 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.6.0 v1.6.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.6.0 v1.6.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.6.0 v1.6.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.6.0 v1.6.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.6.0 v1.6.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.6.0 v1.6.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1 v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7 v3.1.6 Symfony SwiftmailerBundle
symfony/symfony            v3.4.3 v4.0.3 The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 7.1.12 (cli) (built: Dec 14 2017 01:31:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

## Subject

After running a vendors update (sonata-page updates to 3.7.1 and sonata-notification updates to 3.3.1), the `sonata:page:create-snapshots --site=all` does not create snapshot anymore.

## Steps to reproduce
Set sonata-page to 3.7.1 and sonata-notification to 3.3.1, create pages and launch `sonata:page:create-snapshots --site=all` after launching `sonata:page:update-core-routes --site=all`

## Expected results
Snapshots must be generated from created pages using the command line.

## Actual results
None of the created pages generates snapshots using the command line.
Works fine when you create snapshot from admin.

If you put sonata-notification in 3.3.0, snapshots generates successfully using the command line.
I didn't investigate, but I think the problem comes from the createAndPublish method which is called from the command line source code.

**Comment by greg0ire** [comment]
Can you please try downgrading, then upgrading the one you suspect, to confirm it comes from one or the other bundle? And then can you use `git bisect` to pinpoint the offending commit?

**Comment by psyray** [comment]
The commit which introduce the bug is
https://github.com/sonata-project/SonataNotificationBundle/commit/1b75f2a007baa5f47f2917e1eb3e7896b1605c50

**Comment by psyray** [comment]
I tried to remove the two lines added in the commit, problem solved.

I think the problem comes from the **definition** var which is overrided.
Look at the line 32, definition var is created, and it is overrided in the line 37.

**Comment by core23** [comment]
> I think the problem comes from the definition var which is overrided.
> Look at the line 32, definition var is created, and it is overrided in the line 37.

Can you please provide a bugfix @psyray 

> What's the purpose of this modification ?

The purpose is, that all consumer must be public to work in symfony 4. This two lines make do this stuff, if you forgot it.

**Comment by greg0ire** [comment]
@psyray please propose a PR with the following piece of code: `$container->getDefinition($id)->setPublic(true)`. No variable, no override, no problem.

**Comment by psyray** [comment]
Hi,

@greg0ire I confirm that this bug is fixed with your code.

I don't understand why I should made a PR, 
@core23 introduced the bug, he should fix it.

I don't have enough time to do it now so if @core23 could do it, that's fine.

Thanks

**Comment by greg0ire** [comment]
> I don't understand why I should made a PR,

Because you are the one suffering from it, so you can test it, and you probably best understand it. But of course, you don't have to fix it, neither should @core23 . No one has to do anything, it's all based on the kindness of people. So if you could go ahead and kindly make the PR, that would be great.

**Comment by psyray** [comment]
PR submitted
